### ISSUE TITLE
engine.analyse() exits with TimeoutError exception

### ISSUE THREAD

**Issue by robertnurnberg** [niklasf/python-chess#1075]
I am running into the same issue with python3 and pypy3. Below the final error messages from pypy3:

```
Traceback (most recent call last):
  File "../matetools/provepvs.py", line 326, in <module>
    m, pv = ana.analyze_fen(fen, bm, pv)
  File "../matetools/provepvs.py", line 78, in analyze_fen
    info = self.engine.analyse(board, limit, game=board)
  File "/home/rn/.local/lib/pypy3.8/site-packages/chess/engine.py", line 2996, in analyse
    return future.result()
  File "/usr/lib/pypy3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/pypy3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/pypy3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/usr/lib/pypy3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```

I am unsure as to what causes this. Is there a timeout value I can set within python-chess? The `limit` in question is `Limit(time=120.0, depth=150)` and comes in a call to:
```
Analysing "8/7p/8/7p/1p5p/1Kp5/npp5/qrkr1Q2 w - -" (after move d2d1) to Limit(time=120.0, depth=150).
```

**Comment by MarkZH** [comment]
When using a `SimpleEngine` and analyzing with a `Limit(time=X)` time limit, a `TimeoutError` will occur if the engines takes more than `X + 10` seconds to return an analysis result. The default 10 seconds can be changed when creating the `SimpleEngine` using the [`timeout` argument](https://github.com/niklasf/python-chess/blob/6af0ff4c8947486e3e3fa8e83ca88815301aaa37/chess/engine.py#L2811).

**Comment by robertnurnberg** [comment]
Thanks a lot!
