### ISSUE TITLE
Question: EngineTerminatedException

### ISSUE THREAD

**Issue by LocutusOfPenguin** [niklasf/python-chess#154]
Hi,
i recall #153  - and i ihave this:

        try:
            self.engine.stop()
        except chess.uci.EngineTerminatedException:
            logging.error('Engine terminated')
        return self.future.result()

but i get:

ERROR      _base - _invoke_callbacks: exception calling callback for <Future at 0x7536e590 state=finished raised EngineTerminatedException>
Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/opt/picochess/uci/engine.py", line 179, in callback
    self.res = command.result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 1039, in command
    raise EngineTerminatedException()
chess.engine.EngineTerminatedException

My Question is:
Do i need to change the expect to "chess.engine.EngineTerminatedException" or is "uci" still correct?

Thanks.

**Comment by niklasf** [comment]
Both should refer to the same type.

**Comment by LocutusOfPenguin** [comment]
Thanks! Just this "Engine terminated" just not come up..But perhaps the problem lays on different place.
=> close.
