### ISSUE TITLE
Where to put the chess engine's EXE file?

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#220]
I was reading the docs and tried `engine = chess.uci.popen_engine("stockfish")` and got the error below. What am I doing wring and where must the engine's EXE reside in order for this to work?

```
>>> import chess
>>> import chess.uci
>>> engine = chess.uci.popen_engine("stockfish")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python 3.6\lib\site-packages\chess\uci.py", line 1138, in popen_engine
    return _popen_engine(command, engine_cls, setpgrp, _popen_lock, **kwargs)
  File "C:\Program Files\Python 3.6\lib\site-packages\chess\engine.py", line 318, in _popen_engine
    PopenProcess(engine, command, **popen_args)
  File "C:\Program Files\Python 3.6\lib\site-packages\chess\engine.py", line 148, in __init__
    self.process = subprocess.Popen(command, **popen_args)
  File "C:\Program Files\Python 3.6\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python 3.6\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by niklasf** [comment]
In your executable `PATH`.

You can also use `chess.uci.popen_engine("path/to/stockfish")`, or specifically `chess.uci.popen_engine("./stockfish")` for the current working directory. Possibly Windows requires backslashes instead.
