### ISSUE TITLE
Chess960 exception parsing PV

### ISSUE THREAD

**Issue by ddugovic** [niklasf/python-chess#273]
https://github.com/niklasf/python-chess/blob/4bcca71d5ef0c9eba291acf10233861833cac9d7/chess/uci.py#L519

```
ERROR:chess.engine:exception parsing pv
Traceback (most recent call last):
  File "/home/lila/.local/lib/python3.6/site-packages/chess/uci.py", line 519, in _info
    pv.append(board.push_uci(token))
  File "/home/lila/.local/lib/python3.6/site-packages/chess/__init__.py", line 2660, in push_uci
    move = self.parse_uci(uci)
  File "/home/lila/.local/lib/python3.6/site-packages/chess/__init__.py", line 2647, in parse_uci
    raise ValueError("illegal uci: {0} in {1}".format(repr(uci), self.fen()))
```

**Comment by niklasf** [comment]
In theory this should indicate an invalid PV sent by the engine, but I am assuming you're seeing this unexpectedly. What are the steps to reproduce?

**Comment by ddugovic** [comment]
Right now I don't know the simplest duplication steps, but having `lichess-bot` play a chess960 game seems to frequently produce this error message, sometimes even from the starting position (presumably easiest to duplicate if the knights aren't on b1/g1).

**Comment by niklasf** [comment]
`c8c8` is never a legal move, even in Chess960. In Chess960 castling should be a king move to the rook square. Are you running Stockfish?

**Comment by ddugovic** [comment]
Ah, I agree... I can't seem to find that example anymore, but searching my log now I see:

```
Apr 22 15:22:38 vps178028 python3[20563]:   File "/home/turing/.local/lib/python3.5/site-packages/chess/__init__.py", line 2647, in parse_uci
Apr 22 15:22:38 vps178028 python3[20563]:     raise ValueError("illegal uci: {0} in {1}".format(repr(uci), self.fen()))
Apr 22 15:22:38 vps178028 python3[20563]: ValueError: illegal uci: 'e4e5' in r1b2rk1/ppp2ppp/1bn5/3qp3/1P6/3P1N2/P1P2PPP/RNBQ1RK1 w - - 0 10
Apr 22 15:22:38 vps178028 python3[20563]: ERROR:chess.engine:exception parsing pv
--
Apr 22 15:22:38 vps178028 python3[20563]:   File "/home/turing/.local/lib/python3.5/site-packages/chess/__init__.py", line 2647, in parse_uci
Apr 22 15:22:38 vps178028 python3[20563]:     raise ValueError("illegal uci: {0} in {1}".format(repr(uci), self.fen()))
Apr 22 15:22:38 vps178028 python3[20563]: ValueError: illegal uci: 'c6e5' in r1b2rk1/ppp2ppp/1bn5/3qp3/1P6/3P1N2/P1P2PPP/RNBQ1RK1 w - - 0 10
Apr 22 15:22:39 vps178028 python3[20563]: ERROR:chess.engine:exception parsing pv
--
Apr 22 15:22:39 vps178028 python3[20563]:   File "/home/turing/.local/lib/python3.5/site-packages/chess/__init__.py", line 2647, in parse_uci
Apr 22 15:22:39 vps178028 python3[20563]:     raise ValueError("illegal uci: {0} in {1}".format(repr(uci), self.fen()))
Apr 22 15:22:39 vps178028 python3[20563]: ValueError: illegal uci: 'c2c3' in r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R b KQkq - 2 5
Apr 22 15:22:40 vps178028 python3[20563]: ERROR:chess.engine:exception parsing pv
--
Apr 22 15:22:40 vps178028 python3[20563]:   File "/home/turing/.local/lib/python3.5/site-packages/chess/__init__.py", line 2647, in parse_uci
Apr 22 15:22:40 vps178028 python3[20563]:     raise ValueError("illegal uci: {0} in {1}".format(repr(uci), self.fen()))
Apr 22 15:22:40 vps178028 python3[20563]: ValueError: illegal uci: 'c2c3' in r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R b KQkq - 2 5
Apr 22 15:22:40 vps178028 python3[20563]: ERROR:chess.engine:exception parsing bestmove
--
Apr 22 15:22:40 vps178028 python3[20563]:   File "/home/turing/.local/lib/python3.5/site-packages/chess/__init__.py", line 2647, in parse_uci
Apr 22 15:22:40 vps178028 python3[20563]:     raise ValueError("illegal uci: {0} in {1}".format(repr(uci), self.fen()))
Apr 22 15:22:40 vps178028 python3[20563]: ValueError: illegal uci: 'c2c3' in r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R b KQkq - 2 5
Apr 22 15:22:41 vps178028 python3[20563]: ERROR:backoff:Giving up api_post(...) after 1 tries (requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://lichess.org/bot/game/J5uZQLh4/move/None)
```

**Comment by niklasf** [comment]
A log on debug level should offer more insights, for example the complete communication with the engine.

```
logging.basicConfig(level=logging.DEBUG)
```

**Comment by niklasf** [comment]
python-chess v0.23.5 shows more detailed error messages that will help debugging this, even in lieu of verbose logging.
