### ISSUE TITLE
SAN representation doesn't work while reading a game from PGN

### ISSUE THREAD

**Issue by Dedekind125** [niklasf/python-chess#302]
While reading a game from a pgn like is demonstrated at the [Docs](https://python-chess.readthedocs.io/en/latest/pgn.html#chess.pgn.read_game),  i cannot print the san representation of the moves. Here is my test code:
``` python
import chess.pgn

pgn = open("./tfd/test/games.pgn")
game = chess.pgn.read_game(pgn)
board = game.board()

for move in game.main_line():
	board.push(move)
	print(move,board.san(move))
```
Terminal Output:
```
  File "test.py", line 9, in <module>
    print(move,board.san(move))
  File "/usr/local/lib/python3.6/site-packages/chess/__init__.py", line 2410, in san
    return self._algebraic(move)
  File "/usr/local/lib/python3.6/site-packages/chess/__init__.py", line 2458, in _algebraic
    san = PIECE_SYMBOLS[piece].upper()
TypeError: list indices must be integers or slices, not NoneType
```
Also, i find it weird that i comment out the board.push(move) command the output looks like this:
```
e2e4 e4
d7d6 d6
g1f3 Nf3
b8c6 Nc6
f1b5 Bb5
g7g5 g5
h2h4 h4
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print(move,board.san(move))
  File "/usr/local/lib/python3.6/site-packages/chess/__init__.py", line 2410, in san
    return self._algebraic(move)
  File "/usr/local/lib/python3.6/site-packages/chess/__init__.py", line 2458, in _algebraic
    san = PIECE_SYMBOLS[piece].upper()
TypeError: list indices must be integers or slices, not NoneType
```
My pgn file is this:
```
[Event "test"]
[Site "?"]
[Date "2018.08.27"]
[Round "1.1"]
[White "player 1"]
[Black "player 2"]
[Result "*"]
[LiveChessVersion "1.4.8"]
[ECO "B00"]

1. e4 d6 2. Nf3 Nc6 3. Bb5 g5 4. h4 g4 5. Nd4 Bd7 6. Nxc6 Bxc6 7. Bxc6+ bxc6 *

```
Am i doing something wrong or is there a bug?

**Comment by niklasf** [comment]
Hi. Try swapping the two lines in the loop:
```
print(move, board.san(move))
board.push(move)
```
That's because the SAN depends on the position before the move was played.

**Comment by Dedekind125** [comment]
Thats great, thanks!
