### ISSUE TITLE
exception from set_epd when comment contains embedded semicolon

### ISSUE THREAD

**Issue by jdart1** [niklasf/python-chess#340]
Looks like set_epd is throwing an exception on this valid EPD line:

r2qk2r/ppp1b1pp/2n1p3/3pP1n1/3P2b1/2PB1NN1/PP4PP/R1BQK2R w KQkq - bm Nxg5; c0 "ERET.095; Queen sacrifice";

python3 ~/chess/arasan-chess/tools/analyze.py -e /home/jdart/chess/engines/stockfish-9-linux/stockfish -c 4 -H 12000 -m 3 -t 1800 candidates-new4.epd >>candidates-new4.log
Traceback (most recent call last):
  File "/home/jdart/.local/lib/python3.6/site-packages/chess/__init__.py", line 2414, in _parse_epd_ops
    operations[opcode] = int(operand)
ValueError: invalid literal for int() with base 10: 'sacrifice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jdart/.local/lib/python3.6/site-packages/chess/__init__.py", line 2418, in _parse_epd_ops
    operations[opcode] = float(operand)
ValueError: could not convert string to float: 'sacrifice'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jdart/chess/arasan-chess/tools/analyze.py", line 254, in <module>
    sys.exit(main())
  File "/home/jdart/chess/arasan-chess/tools/analyze.py", line 224, in main
    position.ops = position.board.set_epd(line)
  File "/home/jdart/.local/lib/python3.6/site-packages/chess/__init__.py", line 2469, in set_epd
    operations = self._parse_epd_ops(parts.pop(), lambda: type(self)(" ".join(parts) + " 0 1"))
  File "/home/jdart/.local/lib/python3.6/site-packages/chess/__init__.py", line 2438, in _parse_epd_ops
    operations[opcode] = position.parse_san(operand)
  File "/home/jdart/.local/lib/python3.6/site-packages/chess/__init__.py", line 2641, in parse_san
    raise ValueError("invalid san: {}".format(repr(san)))
ValueError: invalid san: 'sacrifice'

(The EPD mentioned is the first line in file "candidates-new4.log").

The script that generates this error is here:

[https://github.com/jdart1/arasan-chess/blob/master/tools/analyze.py](url)

**Comment by niklasf** [comment]
Thanks for reporting. Released in v0.23.11 and v0.24.1.
