### ISSUE TITLE
is_castling always returns false

### ISSUE THREAD

**Issue by infinitelytight** [niklasf/python-chess#341]
```
>>> import chess
>>> 
>>> board = chess.Board()
>>> 
>>> board.push_san("e4")
Move.from_uci('e2e4')
>>> board.push_san("e5")
Move.from_uci('e7e5')
>>> board.push_san("Nf3")
Move.from_uci('g1f3')
>>> board.push_san("Nc6")
Move.from_uci('b8c6')
>>> board.push_san("Bc4")
Move.from_uci('f1c4')
>>> board.push_san("Bc5")
Move.from_uci('f8c5')
>>> board.push_san("O-O")
Move.from_uci('e1g1')
```

The last move in the stack is a castling move: `print(board.peek())` outputs `e1g1`. But `board.is_castling(board.peek())` always outputs `False`.

I wanted to check if the SAN for this move was actually O-O but this raised an error: 

```
>>> print(board.san(board.peek()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.5/site-packages/chess/__init__.py", line 2410, in san
    return self._algebraic(move)
  File "/home/user/.local/lib/python3.5/site-packages/chess/__init__.py", line 2458, in _algebraic
    san = PIECE_SYMBOLS[piece].upper()
TypeError: list indices must be integers or slices,
```

**Comment by niklasf** [comment]
Hi, that's because `board.peek()` is not a legal move on `board` (which already includes the move).

```
>>> import chess
>>> 
>>> board = chess.Board()
>>> 
>>> board.push_san("e4")
Move.from_uci('e2e4')
>>> board.push_san("e5")
Move.from_uci('e7e5')
>>> board.push_san("Nf3")
Move.from_uci('g1f3')
>>> board.push_san("Nc6")
Move.from_uci('b8c6')
>>> board.push_san("Bc4")
Move.from_uci('f1c4')
>>> board.push_san("Bc5")
Move.from_uci('f8c5')
>>> 
>>> move = board.parse_san("O-O")  # don't push just yet
>>> board.is_castling(move)
True
>>> board.san(move)
'O-O'
>>> 
>>> board.push(move)
```
