### ISSUE TITLE
exception in PGN processing reported when header has embedded paren

### ISSUE THREAD

**Issue by jdart1** [niklasf/python-chess#353]
I am seeing a console error from pgn.read_game when parsing the following PGN file with python-chess 0.24.2.

```
ERROR:chess.pgn:error during pgn parsing
Traceback (most recent call last):
  File "/home/jdart/.local/lib/python3.6/site-packages/chess/pgn.py", line 1253, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "/home/jdart/.local/lib/python3.6/site-packages/chess/pgn.py", line 693, in parse_san
    return board.parse_san(san)
  File "/home/jdart/.local/lib/python3.6/site-packages/chess/__init__.py", line 2665, in parse_san
    raise ValueError("invalid san: {}".format(repr(san)))
ValueError: invalid san: '('
ERROR:chess.pgn:error during pgn parsing
Traceback (most recent call last):
  File "/home/jdart/.local/lib/python3.6/site-packages/chess/pgn.py", line 1253, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "/home/jdart/.local/lib/python3.6/site-packages/chess/pgn.py", line 693, in parse_san
    return board.parse_san(san)
  File "/home/jdart/.local/lib/python3.6/site-packages/chess/__init__.py", line 2665, in parse_san
    raise ValueError("invalid san: {}".format(repr(san)))
ValueError: invalid san: ')'
```

If I remove the header:
```
[Opening "St. George (Baker) defense"]
```

then I get no error.

Note that the parsing did complete and no exception was thrown to the calling program. So apparently the reported exception is caught internally.

```
[Event "?"]
[Site "?"]
[Date "2019.01.14"]
[Round "1"]
[White "Stockfish-reference"]
[Black "Stockfish-learning"]
[Result "1-0"]
[ECO "B00"]
[Opening "St. George (Baker) defense"]
[GameDuration "00:40:54"]
[GameEndTime "2019-01-14T07:27:30.802 PST"]
[GameStartTime "2019-01-14T06:46:35.929 PST"]
[PlyCount "154"]
[Termination "adjudication"]
[TimeControl "900+5"]

1. e4 {book} a6 {book} 2. c4 {book} e5 {0.00/31 48s} 3. Nf3 {+0.69/29 36s}
Nc6 {0.00/31 12s} 4. Nc3 {+0.56/28 14s} Nf6 {0.00/30 9.3s} 5. a3 {+0.50/28 29s}
d6 {+0.12/28 21s} 6. Be2 {+0.43/26 16s} Bg4 {+0.14/25 8.8s} 7. d3 {+0.43/28 34s}
g6 {0.00/28 14s} 8. O-O {+0.30/28 20s} Bg7 {+0.15/31 47s} 9. b4 {+0.24/27 13s}
O-O {0.00/26 14s} 10. Rb1 {+0.45/30 24s} Nd7 {-0.03/29 35s}
11. Bg5 {+0.68/25 6.8s} Bf6 {0.00/27 7.9s} 12. Be3 {+0.55/29 16s}
Bg7 {-0.05/30 44s} 13. Bg5 {+0.61/29 26s} Bf6 {0.00/32 8.7s}
14. Be3 {+0.51/29 11s} Bg7 {0.00/34 16s} 15. Qd2 {+0.50/30 22s} a5 {0.00/32 67s}
16. b5 {+0.45/29 7.9s} Bxf3 {0.00/32 6.0s} 17. Bxf3 {+0.51/32 9.4s}
Nd4 {0.00/34 8.9s} 18. Bd1 {+0.66/31 9.5s} Nc5 {-0.09/35 18s}
19. Bxd4 {+0.65/31 12s} exd4 {-0.32/34 37s} 20. Na4 {+0.83/32 29s}
Nd7 {-0.27/32 28s} 21. f4 {+0.78/32 27s} h5 {-0.35/32 21s}
22. Bf3 {+0.85/29 12s} Rb8 {-0.33/29 24s} 23. g3 {+0.81/30 30s}
b6 {-0.48/29 21s} 24. Bg2 {+0.88/29 21s} Nf6 {-0.58/33 46s}
25. Nb2 {+1.03/34 9.1s} Ng4 {-0.58/36 19s} 26. Nd1 {+1.03/34 11s}
Qe7 {-0.58/38 16s} 27. Bf3 {+1.03/37 13s} Nf6 {-0.58/38 7.6s}
28. Nf2 {+1.03/38 12s} Nd7 {-0.58/39 26s} 29. Bg2 {+1.03/38 17s}
Nc5 {-0.58/38 11s} 30. h4 {+1.03/38 15s} Rbe8 {-0.67/38 71s}
31. Kh2 {+1.03/39 15s} Qd8 {-0.67/34 18s} 32. Rbe1 {+1.03/35 12s}
Nd7 {-0.77/38 125s} 33. Qd1 {+1.03/36 16s} Nc5 {-0.87/34 30s}
34. Nh3 {+1.03/37 13s} Kh8 {-0.77/30 14s} 35. Qe2 {+1.03/37 25s}
Nd7 {-0.77/33 5.2s} 36. Ng5 {+1.13/35 44s} Bh6 {-0.77/33 7.8s}
37. Qf2 {+1.24/34 15s} Bg7 {-0.77/34 7.1s} 38. Rd1 {+1.42/31 14s}
Nc5 {-0.87/34 46s} 39. Kh1 {+1.33/32 24s} Kg8 {-0.77/32 9.1s}
40. Nf3 {+1.38/30 9.7s} Nb3 {-0.77/30 4.8s} 41. Bh3 {+1.68/28 14s}
Kh8 {-1.10/31 53s} 42. Rg1 {+1.86/32 46s} Nc5 {-1.01/27 5.0s}
43. g4 {+1.73/30 12s} Qf6 {-1.04/28 18s} 44. Ng5 {+1.78/31 21s}
hxg4 {-1.53/28 8.1s} 45. Rxg4 {+1.87/29 9.6s} Bh6 {-1.45/26 6.1s}
46. Qg3 {+1.86/29 15s} Rg8 {-1.50/29 15s} 47. Rg1 {+1.71/32 44s}
Rg7 {-1.32/29 4.7s} 48. h5 {+1.86/29 6.2s} Kg8 {-1.41/28 6.2s}
49. hxg6 {+1.46/32 27s} fxg6 {-1.25/28 7.8s} 50. Qh4 {+1.61/33 20s}
Bxg5 {-1.42/29 6.6s} 51. Rxg5 {+1.61/35 7.0s} Ne6 {-1.19/28 4.8s}
52. Bxe6+ {+1.61/38 10.0s} Rxe6 {-1.39/32 13s} 53. Kg2 {+1.61/39 15s}
Rh7 {-1.49/29 8.5s} 54. Qg4 {+1.61/41 9.0s} Kf8 {-2.00/31 19s}
55. Rh1 {+2.24/32 7.8s} Rxh1 {-2.01/28 2.5s} 56. Kxh1 {+2.36/35 12s}
Qh8+ {-1.93/29 5.9s} 57. Kg2 {+2.41/36 9.8s} Kf7 {-1.57/29 1.9s}
58. Qf3 {+2.46/37 14s} Rf6 {-2.27/33 13s} 59. e5 {+2.50/33 9.1s}
dxe5 {-2.25/30 2.5s} 60. Qd5+ {+2.87/33 18s} Kg7 {-2.43/30 4.3s}
61. Qd7+ {+2.92/33 7.1s} Rf7 {-2.55/31 5.7s} 62. Qe6 {+3.02/32 8.4s}
Qh6 {-2.48/28 3.7s} 63. Qxe5+ {+3.14/32 7.6s} Kh7 {-2.24/27 1.7s}
64. Qe4 {+3.13/35 13s} Qg7 {-2.39/30 8.2s} 65. Re5 {+3.45/32 6.9s}
Qf8 {-2.65/30 10s} 66. Re8 {+3.78/31 9.5s} Qc5 {-2.65/30 5.5s}
67. Kg3 {+3.99/31 7.7s} a4 {-2.92/31 5.2s} 68. Rd8 {+4.10/31 7.1s}
Re7 {-3.27/29 5.0s} 69. Qxd4 {+4.37/32 9.1s} Qxd4 {-3.28/27 2.5s}
70. Rxd4 {+4.41/29 7.3s} Kg7 {-3.62/31 7.5s} 71. Re4 {+5.72/31 7.3s}
Rd7 {-4.53/29 5.0s} 72. d4 {+6.17/33 8.0s} Rd8 {-5.41/32 5.0s}
73. Kg4 {+6.31/39 6.0s} Kf7 {-5.92/29 5.0s} 74. d5 {+7.67/39 36s}
Rh8 {-6.63/29 5.0s} 75. Re6 {+7.97/28 6.8s} Rh1 {-7.12/26 5.0s}
76. Rc6 {+8.52/27 8.6s} Rg1+ {-7.80/24 5.0s} 77. Kf3 {+8.86/27 6.4s}
Rf1+ {-8.11/24 5.0s, White wins by adjudication} 1-0
```

**Comment by niklasf** [comment]
Thanks for reporting. Surprisingly I cannot reproduce this locally. I added the PGN to the test suite to see if it is maybe specific to a particular Python version.

> Note that the parsing did complete and no exception was thrown to the calling program. So apparently the reported exception is caught internally.

At least that part is [expected](https://python-chess.readthedocs.io/en/latest/pgn.html#chess.pgn.GameCreator.handle_error).

**Comment by niklasf** [comment]
Aha! My guess is your source file contains a BOM (which is not a valid header, so the following  content is interpreted as movetext). The proper way to open the file would be `open("filename.pgn", encoding="utf-8-sig")`.

**Comment by jdart1** [comment]
Thanks for the rapid response. The file content is actually sent in a request and then read with StringIO. I don't see a way to specify the encoding for StringIO.
