### ISSUE TITLE
illegal uci handling

### ISSUE THREAD

**Issue by ChrisWhittington** [niklasf/python-chess#369]
Board position and fen below.
Here I typed in an illegal move f7e6 instead of f7d6 mate by double discovered check.
Python broke in my line number 236: move = board.parse_uci(mv), when I think it ought to return me a ValueError. Not sure if I am doing something stupid, or the situation related to the discovered checks and mates and so on.

Code:
```python
                mv = input('move:')
                move = board.parse_uci(mv)
                if (move==ValueError):
                    continue
                if (move in board.legal_moves):
                    break
```
```
r n . q k b n .
p p p b p N p .
. . . p Q . . .
. . P . . P B B
. . . P P . . .
. . N . . . . .
P P . . . . P P
R . . . . R K .
move:f7e6
Traceback (most recent call last):
  File "C:\Users\chris\source\repos\Python_Chess_01\Python_Othello_01\Python_Chess_01.py", line 562, in <module>
    main()
  File "C:\Users\chris\source\repos\Python_Chess_01\Python_Othello_01\Python_Chess_01.py", line 236, in main
    move = board.parse_uci(mv)
  File "C:\Users\chris\Anaconda3\lib\site-packages\chess\__init__.py", line 2728, in parse_uci
    raise ValueError("illegal uci: {!r} in {}".format(uci, self.fen()))
ValueError: illegal uci: 'f7e6' in rn1qkbn1/pppbpNp1/3pQ3/2P2PBB/3PP3/2N5/PP4PP/R4RK1 w q - 1 19
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x0000024AB410E7B8>>
Traceback (most recent call last):
  File "C:\Users\chris\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 738, in __del__
TypeError: 'NoneType' object is not callable
Press any key to continue . . .
```

**Comment by niklasf** [comment]
It throws `ValueError` instead of returning it. Usage could be like:

```python
try:
    move = board.parse_uci(mv)
    break
except ValueError:
    continue
```

(Side note: `move in board.legal_moves` is guaranteed if `board.parse_uci()` suceeds).
