### ISSUE TITLE
Write high level documentation or recipes

### ISSUE THREAD

**Issue by niklasf** [niklasf/python-chess#371]
Currently the documentation is built like a reference. Some kind of overview or collection of recipes might be helpful.

---
Prompted by this email (in German), with some suggestions:
![image](https://user-images.githubusercontent.com/402777/53901679-d0b2b200-403f-11e9-9a29-93c986e2b533.png)

**Comment by scitronboy** [comment]
What/who is that email from/for???

**Comment by ChrisWhittington** [comment]
some more bits of sample source code would be very useful

**Comment by WolfgangFahl** [comment]
I've started a bit of this at http://wiki.bitplan.com/index.php/Python-chess

**Comment by WolfgangFahl** [comment]
At this time I've got four engines to try things with with on my mac: gnuchess, stockfish, crafty and xboard. For gnuchess and stockfish I successfully let the engines play against themselves. crafty doesn't seem to support any of the python-chess protocols uci or xboard so I am not pursuing anything with that engine yet.

Now I'd like to use xboard just as a GUI and I don't know how to do that I'd like to do simple session command like http://wiki.bitplan.com/index.php/XBoard#Session_example but when I open xboard with the XBoardProtocol with a SimpleEngine I get <XBoardProtocol (pid=9460)>: Timeout during initialization - is that a separate bug or do i just need some sample code here?

**Comment by ChrisWhittington** [comment]
I found the same. Most stuff works except Crafty (and different Craftys don’t work in different ways). However some people do manage to overcome the problems, Ferdinand Mosca, I think, being one.

One Crafty problem is declined to send any PV before one million nodes done, and quite often declines to send a PV anyway. I gave up with it.

**Comment by niklasf** [comment]
@WolfgangFahl To investigate the issue, can you please share the exact Python code and engine version that leads to `<XBoardProtocol (pid=9460)>: Timeout during initialization`?

**Comment by WolfgangFahl** [comment]
@niklasf: 

see
https://github.com/WolfgangFahl/play-chess-with-a-webcam/blob/master/tests/test_chessengine.py

I am currently experimenting with this on linux and mac and also get different other issues like Threads hanging

**Comment by WolfgangFahl** [comment]
I have now added some code to show the hanging issue add the end see https://github.com/WolfgangFahl/play-chess-with-a-webcam/commit/bcaafe3

**Comment by niklasf** [comment]
* For the hanging threads: It looks like test engines is starting some engines, but never closing them. When using SimpleEngine (as opposed to asyncio), the background thread will live as long as the engine.

* For the timeout: Afaik `xboard` itself is not an XBoard engine, so it does not declare itself as an XBoard engine within the allotted time.

**Comment by WolfgangFahl** [comment]
How do i close the engines? When calling quit() i get another error: 
```
chess engine GNU Chess called via gnuchess at /Users/wf/bin/gnuchess
Close running child process: kill <_UnixSubprocessTransport closed pid=18268 running stdin=<_UnixWritePipeTransport closing fd=7 idle bufsize=0> stdout=<_UnixReadPipeTransport closing fd=8 idle> stderr=<_UnixReadPipeTransport closing fd=10 idle>>
Traceback (most recent call last):
  File "/Users/wf/Documents/pyworkspace/PlayChessWithAWebCam/tests/test_chessengine.py", line 85, in <module>
    test_engines()
  File "/Users/wf/Documents/pyworkspace/PlayChessWithAWebCam/tests/test_chessengine.py", line 46, in test_engines
    chessEngine.close()    
  File "/Users/wf/Documents/pyworkspace/PlayChessWithAWebCam/pcwawc/chessengine.py", line 76, in close
    self.engine.quit()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chess/engine.py", line 2350, in quit
    return future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

Do i have to echo some commands into xboard to make xboard behave properly?
Is there a gitter chat or something similar for this project?

**Comment by niklasf** [comment]
There wasn't so far, but why not ... created https://gitter.im/python-chess/community.

It looks like `gnuchess` does not even support the standard `quit` command. You can do `engine.close()` to shut it down forcefully. I did not anticipate that, but after 95aade7e46724126bd0a2a7a66c5697c9a5e0f22 the next version of python-chess will support doing
```python
try:
    engine.quit()  # Ask nicely
except asyncio.TimeoutError:
    engine.close()  # Force close
```

I don't know what you're trying to achieve with `xboard`. It's a GUI, not an engine.

**Comment by PedanticHacker** [comment]
The documentation is fine as it is. This could be closed.

**Comment by HanifRoi** [comment]
gka tau bang
