### ISSUE TITLE
Rare Error using info from Stockfish

### ISSUE THREAD

**Issue by jjoshua2** [niklasf/python-chess#400]
Doing 100k 0.1 second SF (Latest Brainfish) analyses and got this occasionally. I'm guessing on longer PVs SF does autowrap to avoid being over 80 characters or something and due to being windows system uses /r and python-chess doesn't support this...
```
exception parsing pv from info: 'depth 111 seldepth 3 multipv 1 score cp 0 nodes 57491 nps 19163666 tbhits 0 time 3 pv f5g4 c1d2\r', position at root: 8/8/2p5/1pP2b2/1P6/4K2k/8/2B5 b - - 98 413
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\engine.py", line 1367, in _parse_uci_info
    pv.append(board.push_uci(token))
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\__init__.py", line 2808, in push_uci
    move = self.parse_uci(uci)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\__init__.py", line 2786, in parse_uci
    move = Move.from_uci(uci)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\__init__.py", line 514, in from_uci
    promotion = PIECE_SYMBOLS.index(uci[4])
ValueError: '\r' is not in list```

**Comment by Mk-Chan** [comment]
Doesn't seem like it actually https://github.com/official-stockfish/Stockfish/blob/master/src/search.cpp#L1606

Not sure what the cause of that is.

**Comment by niklasf** [comment]
Thanks for reporting. This might have happened when a Windows line ending (`\r\n`) arrived seperately in the read buffer, i.e. first `\r`, then `\n`.
