### ISSUE TITLE
Async Error

### ISSUE THREAD

**Issue by jjoshua2** [niklasf/python-chess#402]
After over 300k successful 0.1 second SF evals, got this error. It appears to be when using async io locks improperly, but I'm just using SimpleEngine so I shouldn't have to deal with that.

```Traceback (most recent call last):
  File ".\fenAnalyze.py", line 26, in <module>
    info = engine.analyse(position, chess.engine.Limit(time=0.1))
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\engine.py", line 2255, in analyse
    return future.result()
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\asyncio\tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
Exception in callback EngineProtocol._line_received('bestmove c5f5 ponder a5a4')
handle: <Handle EngineProtocol._line_received('bestmove c5f5 ponder a5a4')>
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\engine.py", line 617, in _line_received
    self.command._line_received(self, line)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\engine.py", line 871, in _line_received
    self.line_received(engine, line)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\engine.py", line 1254, in line_received
    self._bestmove(engine, line.split(" ", 1)[1])
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\engine.py", line 1275, in _bestmove
    self.analysis.set_finished()
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\engine.py", line 2054, in set_finished
    self._finished.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
```

**Comment by niklasf** [comment]
From the backtrace it looks like this are two seperate problems:

```
  File ".\fenAnalyze.py", line 26, in <module>
    info = engine.analyse(position, chess.engine.Limit(time=0.1))
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\engine.py", line 2255, in analyse
    return future.result()
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\asyncio\tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

This would indicate that Stockfish took 0.1s + 10s (default timeout) to respond with the best move.

The timeout can be increased or disabled in the [`SimpleEngine` constructors](https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.SimpleEngine). Or you could catch the `asyncio.TimeoutError` and log the position to see if it is random or reproducible.

```
Exception in callback EngineProtocol._line_received('bestmove c5f5 ponder a5a4')
handle: <Handle EngineProtocol._line_received('bestmove c5f5 ponder a5a4')>
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\engine.py", line 617, in _line_received
    self.command._line_received(self, line)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\engine.py", line 871, in _line_received
    self.line_received(engine, line)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\engine.py", line 1254, in line_received
    self._bestmove(engine, line.split(" ", 1)[1])
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\engine.py", line 1275, in _bestmove
    self.analysis.set_finished()
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\chess\engine.py", line 2054, in set_finished
    self._finished.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
```

This is an internal error in python-chess and a bug: Stockfish finally responded with `bestmove`, but python-chess was no longer expecting it. Will fix.

**Comment by jjoshua2** [comment]
I think it must due to a delayed TB hit(s). A 1 in a million event of it being very delayed to a combination of factors.
