### ISSUE TITLE
Exception handling when variant is unidentified.

### ISSUE THREAD

**Issue by spinor8** [niklasf/python-chess#421]
Hi, I usually have some large pgns containing a few games with variants. So for a minimal concrete verifiable example, consider the following PGN.

```
[Event "Live Chess - Three-Check"]
[Site "Chess.com"]
[Date "2016.05.23"]
[Round "-"]
[White "sutkin"]
[Black "K78"]
[Result "0-1"]
[Variant "3-check"]
[SetUp "1"]
[FEN "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 +0+0"]
[ECO "B10"]
[ECOUrl "https://www.chess.com/openings/B10-Caro-Kann-Defense-2.Nc3"]
[CurrentPosition "r4r2/p4p1k/1qpR2p1/4p3/4P1Qp/1P4K1/P1P1B1P1/R7 w - -"]
[Timezone "UTC"]
[UTCDate "2016.05.23"]
[UTCTime "19:05:29"]
[WhiteElo "1200"]
[BlackElo "2546"]
[TimeControl "120+1"]
[Termination "K78 won by checking the opponent king for the 3rd time"]
[StartTime "19:05:29"]
[EndDate "2016.05.23"]
[EndTime "19:10:08"]
[Link "https://www.chess.com/live/game/1589517193"]

1. e4 {[%clk 0:01:59.1]} 1... c6 {[%clk 0:01:50.7]} 2. Nc3 {[%clk 0:01:55.7]} 2... d6 {[%clk 0:01:47.1]}

[Event "Live Chess"]
[Site "Chess.com"]
[Date "2018.05.05"]
[White "tg123"]
[Black "elmo"]
[Result "1-0"]
[ECO "A08"]
[WhiteElo "2051"]
[BlackElo "2072"]
[TimeControl "180"]
[EndTime "2:30:34 PDT"]
[Termination "tg123 won by resignation"]
[CurrentPosition "r7/pp1N2kp/3b2p1/2p2nB1/2Pp4/3P3B/PP5P/R3Q1K1 b - - 0 24"]

1.g3 {[%clk 0:02:59]} d5 {[%clk 0:02:58]} 2.Bg2 {[%clk 0:02:59]} c5 {[%clk 0:02:57]} 3.Nf3 {[%clk 0:02:59]}
```
I want to scan through them. So I use a while loop and put in a try-except like the following

```
import chess.pgn
pgn = open("eg_3check.pgn")

while True:
    try:
        g = chess.pgn.read_game(pgn)
        if g is None:
            break
    except:
        print("Excepted game")
        continue
```

I still get the error message printed out.
```
error during pgn parsing
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\py37chess\lib\site-packages\chess\pgn.py", line 1164, in read_game
    VariantBoard = headers.variant()
  File "C:\ProgramData\Miniconda3\envs\py37chess\lib\site-packages\chess\pgn.py", line 560, in variant
    return find_variant(self["Variant"])
  File "C:\ProgramData\Miniconda3\envs\py37chess\lib\site-packages\chess\variant.py", line 867, in find_variant
    raise ValueError("unsupported variant: {}".format(name))
ValueError: unsupported variant: 3-check
error during pgn parsing
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\py37chess\lib\site-packages\chess\pgn.py", line 1172, in read_game
    board_stack = [VariantBoard(fen, chess960=headers.is_chess960())]
  File "C:\ProgramData\Miniconda3\envs\py37chess\lib\site-packages\chess\__init__.py", line 1394, in __init__
    self.set_fen(fen)
  File "C:\ProgramData\Miniconda3\envs\py37chess\lib\site-packages\chess\__init__.py", line 2247, in set_fen
    raise ValueError("fen string has more parts than expected: {!r}".format(fen))
ValueError: fen string has more parts than expected: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 +0+0'
Traceback (most recent call last):
  File "D:/GitRepos/chess/eg_pychess_troubleshoot_3check.py", line 26, in <module>
    board = first_game.board()
AttributeError: 'NoneType' object has no attribute 'board'
```

When I check the code, there is a raise ValueError in getting the variant but the exception is caught further up in pgn.py. So in essence it is skipping the game but still spewing out the exception messages.

That's not ideal because of the error messages that get logged. I was wondering what's the best way of doing it. Maybe make the error message less threatening as it really looks like an unhandled exception. Perhaps, create a flag to turn on the exception and let the user handle it. What do you think?

**Comment by niklasf** [comment]
Thanks. For this concrete issue I added `3-check` as an alias for `Three-Check`, so PGNs from chess.com should work now.

Generally, there are multiple ways to hook into error handling. I added some examples here: https://python-chess.readthedocs.io/en/latest/pgn.html#chess.pgn.GameBuilder.handle_error

**Comment by spinor8** [comment]
Thanks for the tip.
