### ISSUE TITLE
syntax error on windows 10

### ISSUE THREAD

**Issue by RandyLov** [niklasf/python-chess#455]
when importing board i get this error

```
C:\Users\Randy\Desktop\puzzlemaker>make_puzzles.py --pgn games.pgn
Traceback (most recent call last):
  File "C:\Users\Randy\Desktop\puzzlemaker\make_puzzles.py", line 10, in <module>
    from chess import Board
  File "C:\Users\Randy\Desktop\puzzlemaker\chess\__init__.py", line 57
    "R": u"\u2656", "r": u"\u265c",
              ^
SyntaxError: invalid syntax
```

has something to do with the unicode chess symbol

**Comment by niklasf** [comment]
What's your Python version?
