### ISSUE TITLE
Module asyncio has no attribute 'run' 

### ISSUE THREAD

**Issue by akhmadzaki** [niklasf/python-chess#456]
I am running this example of the chess engine playing against itself (in my case it's Stockfish 10) from the docs.

```
import asyncio
import chess
import chess.engine

async def main():
    transport, engine = await chess.engine.popen_uci("C:\\Chess-Engine\\stockfish-10-win\\Windows\\stockfish_10_x64.exe")

    board = chess.Board()
    while not board.is_game_over():
        result = await engine.play(board, chess.engine.Limit(time=0.1))
        board.push(result.move)

    await engine.quit()

asyncio.set_event_loop_policy(chess.engine.EventLoopPolicy())
asyncio.run(main())
```

After i ran the code, i got this error.

```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    asyncio.run(main())
AttributeError: module 'asyncio' has no attribute 'run'
```

I'm running the code using Python 3.6.5 version for Windows 10 64 bit.

**Comment by Harmon758** [comment]
[`asyncio.run`](https://docs.python.org/3/library/asyncio-task.html#asyncio.run) was added in Python 3.7.

**Comment by niklasf** [comment]
Since older Python versions are otherwise supported, I should mention the alternative:

```python
import contextlib

# [...]

with contextlib.closing(asyncio.get_event_loop()) as loop:              
    loop.run_until_complete(main())
```

**Comment by akhmadzaki** [comment]
I ran the alternative code.

```
import asyncio
import chess
import chess.engine
import contextlib

async def main():
    transport, engine = await chess.engine.popen_uci("C:\\Chess-Engine\\stockfish-10-win\\Windows\\stockfish_10_x64.exe")

    board = chess.Board()
    while not board.is_game_over():
        result = await engine.play(board, chess.engine.Limit(time=0.1))
        board.push(result.move)

    await engine.quit()

with contextlib.closing(asyncio.get_event_loop()) as loop:              
    loop.run_until_complete(main())
```

and got this error.

```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    loop.run_until_complete(main())
  File "C:\Users\HP\Anaconda3\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "test.py", line 7, in main
    transport, engine = await chess.engine.popen_uci("C:\\Chess-Engine\\stockfish-10-win\\Windows\\stockfish_10_x64.exe")
  File "C:\Users\HP\Anaconda3\lib\site-packages\chess\engine.py", line 2247, in popen_uci
    transport, protocol = await UciProtocol.popen(command, setpgrp=setpgrp, loop=loop, **popen_args)
  File "C:\Users\HP\Anaconda3\lib\site-packages\chess\engine.py", line 895, in popen
    return await loop.subprocess_exec(cls, *command, **popen_args)
  File "C:\Users\HP\Anaconda3\lib\asyncio\base_events.py", line 1192, in subprocess_exec
    bufsize, **kwargs)
  File "C:\Users\HP\Anaconda3\lib\asyncio\coroutines.py", line 212, in coro
    res = func(*args, **kw)
  File "C:\Users\HP\Anaconda3\lib\asyncio\base_events.py", line 341, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
```

**Comment by niklasf** [comment]
You still need to set the event loop policy with

```python
asyncio.set_event_loop_policy(chess.engine.EventLoopPolicy())
```

before getting the event loop.

**Comment by akhmadzaki** [comment]
Now i got this error.

```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    loop.run_until_complete(main())
  File "C:\Users\HP\Anaconda3\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "test.py", line 7, in main
    transport, engine = await chess.engine.popen_uci("C:\\Chess-Engine\\stockfish-10-win\\Windows\\stockfish_10_x64.exe")
  File "C:\Users\HP\Anaconda3\lib\site-packages\chess\engine.py", line 2247, in popen_uci
    transport, protocol = await UciProtocol.popen(command, setpgrp=setpgrp, loop=loop, **popen_args)
  File "C:\Users\HP\Anaconda3\lib\site-packages\chess\engine.py", line 895, in popen
    return await loop.subprocess_exec(cls, *command, **popen_args)
  File "C:\Users\HP\Anaconda3\lib\asyncio\base_events.py", line 1192, in subprocess_exec
    bufsize, **kwargs)
  File "C:\Users\HP\Anaconda3\lib\asyncio\windows_events.py", line 378, in _make_subprocess_transport
    **kwargs)
  File "C:\Users\HP\Anaconda3\lib\asyncio\base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "C:\Users\HP\Anaconda3\lib\asyncio\windows_events.py", line 762, in _start
    bufsize=bufsize, **kwargs)
  File "C:\Users\HP\Anaconda3\lib\asyncio\windows_utils.py", line 205, in __init__
    stderr=stderr_wfd, **kwds)
  File "C:\Users\HP\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\HP\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

It seems like the program cannot find the engine executable file.

The code.

```
import asyncio
import chess
import chess.engine
import contextlib

async def main():
    transport, engine = await chess.engine.popen_uci("C:\\Chess-Engine\\stockfish-10-win\\Windows\\stockfish_10_x64.exe")

    board = chess.Board()
    while not board.is_game_over():
        result = await engine.play(board, chess.engine.Limit(time=0.1))
        board.push(result.move)

    await engine.quit()

asyncio.set_event_loop_policy(chess.engine.EventLoopPolicy())
with contextlib.closing(asyncio.get_event_loop()) as loop:              
    loop.run_until_complete(main())
```

**Comment by niklasf** [comment]
Assuming the file exsists, I will have to check how to specify subprocess paths on Windows (which I currently do not have access to). How about "C:/Chess-Engine/..."?

**Comment by akhmadzaki** [comment]
I'm sorry earlier i mistyped the file path so that's why the program cannot find it. After i fixed it the program worked. Both "/" and "\\" worked to specify the file path.
