### ISSUE TITLE
Timeout during initialization of GNU Chess 6.2.7

### ISSUE THREAD

**Issue by hasnul** [niklasf/python-chess#572]
Per subject; log snippet:

```
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:chess.engine:<XBoardProtocol (pid=686154)>: Connection made
DEBUG:chess.engine:<XBoardProtocol (pid=686154)>: << xboard
DEBUG:chess.engine:<XBoardProtocol (pid=686154)>: << protover 2
DEBUG:chess.engine:<XBoardProtocol (pid=686154)>: >> GNU Chess 6.2.7
DEBUG:chess.engine:<XBoardProtocol (pid=686154)>: >> Copyright (C) 2020 Free Software Foundation, Inc.
DEBUG:chess.engine:<XBoardProtocol (pid=686154)>: >> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
DEBUG:chess.engine:<XBoardProtocol (pid=686154)>: >> This is free software: you are free to change and redistribute it.
DEBUG:chess.engine:<XBoardProtocol (pid=686154)>: >> There is NO WARRANTY, to the extent permitted by law.
ERROR:chess.engine:<XBoardProtocol (pid=686154)>: Timeout during initialization
```
Traceback:

```
/home/hasnul/.local/share/virtualenvs/checkmate-hKTXJQjr/lib/python3.8/site-packages/chess/engine.py:171: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
  warnings.warn("A loop is being detached from a child watcher with pending handlers", RuntimeWarning)
Traceback (most recent call last):
  File "gnutest.py", line 5, in <module>
    chess.engine.SimpleEngine.popen_xboard('./gnuchess')
  File "/home/hasnul/.local/share/virtualenvs/checkmate-hKTXJQjr/lib/python3.8/site-packages/chess/engine.py", line 2448, in popen_xboard
    return cls.popen(XBoardProtocol, command, timeout=timeout, debug=debug, setpgrp=setpgrp, **popen_args)
  File "/home/hasnul/.local/share/virtualenvs/checkmate-hKTXJQjr/lib/python3.8/site-packages/chess/engine.py", line 2432, in popen
    return run_in_background(background, name=f"{cls.__name__} (command={command!r})", debug=debug)
  File "/home/hasnul/.local/share/virtualenvs/checkmate-hKTXJQjr/lib/python3.8/site-packages/chess/engine.py", line 217, in run_in_background
    return future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/hasnul/.local/share/virtualenvs/checkmate-hKTXJQjr/lib/python3.8/site-packages/chess/engine.py", line 211, in background
    _run(coroutine(future))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/hasnul/.local/share/virtualenvs/checkmate-hKTXJQjr/lib/python3.8/site-packages/chess/engine.py", line 2424, in background
    await asyncio.wait_for(protocol.initialize(), timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/home/hasnul/.local/share/virtualenvs/checkmate-hKTXJQjr/lib/python3.8/site-packages/chess/engine.py", line 1652, in initialize
    return await self.communicate(XBoardInitializeCommand)
  File "/home/hasnul/.local/share/virtualenvs/checkmate-hKTXJQjr/lib/python3.8/site-packages/chess/engine.py", line 768, in communicate
    return await command.result
chess.engine.EngineError: xboard engine did not declare required feature: ping
```

**Comment by niklasf** [comment]
I tried with `popen_xboard(["gnuchess", "--xboard"])`, but it looks like it lacks the essential ping feature even then.

`popen_uci(["gnuchess", "--uci"])` seems to work.

**Comment by hasnul** [comment]
I have some doubts about the stability of this GNU Chess version. I tried playing it in XBoard gui and after the first move and my response, it didn't produce any more moves. I'm going to try and compile version 5. But I think this issue can be closed.
