### ISSUE TITLE
The build of Stockfish+NNUE engine crashes if using python-chess

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#609]
So I updated to the latest build of Stockfish beta from [here](https://abrok.eu/stockfish). And now my Stockfish engine is crashing at move 1 in my chess GUI. As tested, `python-chess` is not yet ready to support `Stockfish+NNUE`.

From the link:
```
Author: Joost VandeVondele
Date: Thu Aug 20 21:14:32 2020 +0200
Timestamp: 1597950872

Set Use NNUE by default to true
```
I am sure [this commit](https://github.com/official-stockfish/Stockfish/commit/daac86691de55fe388b9b727794c7d27f2b90d5c) to the Stockfish engine is to blame. (And yes, I have the NNUE file alongside Stockfish's engine file, but my chess GUI still crashes.)

Python's traceback, if using the newest Stockfish+NNUE engine, is this:
```
Traceback (most recent call last):
  File "C:\Users\Boštjan\Desktop\Chess Fighter\source\window.py", line 663, in invoke
    result = self.stockfish.play(
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 2386, in play
    return future.result()
  File "C:\Program Files\Python38\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Program Files\Python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Program Files\Python38\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1316, in play
    return await self.communicate(UciPlayCommand)
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 768, in communicate
    return await command.result
chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 1)
[Finished in 4.0s with exit code 3221226505]
[shell_cmd: python -u "C:\Users\Boštjan\Desktop\Chess Fighter\run.py"]
[dir: C:\Users\Boštjan\Desktop\Chess Fighter]
[path: C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\]
```
@niklasf, how can we improve python-chess to support Stockfish+NNUE?

**Comment by PedanticHacker** [comment]
I thought it was something wrong with python-chess. I apologize! I had to add the `EvalFile` engine option and provide the path to the NNUE file. Thanks, @Hungry-Caterpillar, for this insight! 👍  Anyway, now it works.
