### ISSUE TITLE
I don't think the engine respects the turn

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#643]
As you can see from the 2 consecutive tracebacks below, the engine (official Stockfish 12 with a default NNUE file) gets a chessboard position (a `chess.Board()` instance) that clearly indicates the turn of the current position on the board (`black's turn`), but it sends a move for white (`g1f3`) and then my application crashes. What is happening here? Am I missing something? My GitHub repo is [here](https://github.com/PedanticHacker/ChessFighter).

```
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1455, in _parse_uci_bestmove
    move = board.push_uci(tokens[0].lower())
  File "C:\Program Files\Python38\lib\site-packages\chess\__init__.py", line 2920, in push_uci
    move = self.parse_uci(uci)
  File "C:\Program Files\Python38\lib\site-packages\chess\__init__.py", line 2907, in parse_uci
    raise ValueError(f"illegal uci: {uci!r} in {self.fen()}")
ValueError: illegal uci: 'g1f3' in rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Boštjan\Desktop\Chess Fighter\source\window.py", line 691, in invoke
    result = self.engine.play(
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 2355, in play
    return future.result()
  File "C:\Program Files\Python38\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Program Files\Python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Program Files\Python38\lib\asyncio\tasks.py", line 491, in wait_for
    return fut.result()
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1284, in play
    return await self.communicate(UciPlayCommand)
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 736, in communicate
    return await command.result
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 947, in _line_received
    self.line_received(engine, line)
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1241, in line_received
    self._bestmove(engine, line.split(" ", 1)[1])
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1260, in _bestmove
    best = _parse_uci_bestmove(engine.board, arg)
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1457, in _parse_uci_bestmove
    raise EngineError(err)
chess.engine.EngineError: illegal uci: 'g1f3' in rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
```

**Comment by niklasf** [comment]
Please also provide the corresponding debug log: https://python-chess.readthedocs.io/en/latest/engine.html#logging

I suspect that the board may be concurrently modified. If so, one way to fix this would be passing a copy (`board.copy()`) to the thread.

**Comment by PedanticHacker** [comment]
That's the debug log.

```
DEBUG:chess.engine:<UciProtocol (pid=1012)>: << ucinewgame
DEBUG:chess.engine:<UciProtocol (pid=1012)>: << isready
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> readyok
DEBUG:chess.engine:<UciProtocol (pid=1012)>: << position startpos moves e2e4
DEBUG:chess.engine:<UciProtocol (pid=1012)>: << go movetime 1000
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info string NNUE evaluation using source/engines/Windows/nn-82215d0fd0df.nnue enabled
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 1 seldepth 1 multipv 1 score cp -15 nodes 128 nps 128000 tbhits 0 time 1 pv c7c5
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 2 seldepth 2 multipv 1 score cp 14 nodes 266 nps 266000 tbhits 0 time 1 pv c7c5 c2c3
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 3 seldepth 3 multipv 1 score cp -13 nodes 800 nps 800000 tbhits 0 time 1 pv e7e5 d2d4 e5d4
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 4 seldepth 4 multipv 1 score cp -54 nodes 2219 nps 1109500 tbhits 0 time 2 pv e7e6 d2d4 c7c5 d4d5
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 5 seldepth 5 multipv 1 score cp -54 nodes 3517 nps 1758500 tbhits 0 time 2 pv e7e6 d2d4 c7c5 d4d5 e6d5
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 6 seldepth 6 multipv 1 score cp -44 nodes 9170 nps 2292500 tbhits 0 time 4 pv c7c5 g1f3 e7e6 c2c3 b8c6
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 7 seldepth 7 multipv 1 score cp -44 nodes 9866 nps 2466500 tbhits 0 time 4 pv c7c5 g1f3 e7e6 c2c3 b8c6 d2d4 c5d4
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 8 seldepth 14 multipv 1 score cp -65 nodes 22750 nps 3250000 tbhits 0 time 7 pv c7c5 g1f3 g7g6 d2d4 c5d4 d1d4 g8f6 e4e5 b8c6
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 9 seldepth 14 multipv 1 score cp -37 nodes 34450 nps 3445000 tbhits 0 time 10 pv c7c5 c2c3 d7d5 e4d5 d8d5 d2d4 c5d4
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 10 seldepth 12 multipv 1 score cp -40 nodes 46914 nps 3351000 tbhits 0 time 14 pv c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6 b1c3 c8d7 c1e3
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 11 seldepth 15 multipv 1 score cp -40 nodes 151452 nps 2912538 tbhits 0 time 52 pv e7e5 g1f3 d7d6 f1c4 f8e7 b1c3 g8f6 d2d4 e5d4 f3d4
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 12 seldepth 16 multipv 1 score cp -18 nodes 202848 nps 2741189 tbhits 0 time 74 pv e7e5 g1f3 g8f6 b1c3 b8c6 d2d4 e5d4 f3d4 f8b4 d4c6
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 13 seldepth 21 multipv 1 score cp -25 nodes 403029 nps 2503285 tbhits 0 time 161 pv e7e5 g1f3 b8c6 b1c3 g8f6 f1b5 f8d6 d2d4 e5d4 f3d4 e8g8 d4f5 d6b4 e1g1
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 14 seldepth 23 multipv 1 score cp -31 nodes 525267 nps 2549839 tbhits 0 time 206 pv e7e5 g1f3 b8c6 f1b5 g8f6 e1g1 f8c5 d2d3 d8e7 c2c3 c5b6 d3d4 e5d4 c3d4 f6e4
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 15 seldepth 22 multipv 1 score cp -37 nodes 832192 nps 2552736 tbhits 0 time 326 pv e7e5 g1f3 b8c6 f1b5 a7a6 b5c6 d7c6 e1g1 d8e7 d2d4 e5d4 f3d4 g8f6 e4e5 f6d5
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 16 seldepth 22 multipv 1 score cp -21 nodes 1117229 nps 2598206 tbhits 0 time 430 pv e7e5 g1f3 b8c6 f1c4 f8c5 b1c3 g8f6 d2d3 h7h6 e1g1 e8g8 h2h3 f8e8 c1d2 c5b6
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 17 seldepth 23 multipv 1 score cp -24 nodes 1928956 nps 2697840 tbhits 0 time 715 pv e7e5 g1f3 b8c6 f1c4 f8c5 d2d3 d7d6 c2c3 g8f6 b2b4 c5b6 a2a4 a7a6 a4a5 b6a7 b1d2 e8g8 c4b3 g8h8 e1g1
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 18 seldepth 26 multipv 1 score cp -20 nodes 2691220 nps 2791721 tbhits 0 time 964 pv e7e5 g1f3 b8c6 f1c4 f8c5 d2d3 d7d6 c2c3 g8f6 b2b4 c5b6 a2a4 a7a5 b4b5 c6e7 b1a3 e7g6 e1g1 h7h6 c4b3
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 19 seldepth 26 multipv 1 score cp -20 nodes 2808086 nps 2799686 hashfull 10 tbhits 0 time 1003 pv e7e5 g1f3 b8c6 f1c4 f8c5 d2d3 d7d6 c2c3 g8f6 b2b4 c5b6 a2a4 a7a5 b4b5 c6e7 b1a3 e7g6 e1g1 h7h6 c4b3
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> bestmove e7e5 ponder g1f3
DEBUG:chess.engine:<UciProtocol (pid=1012)>: << position startpos moves e2e4 e7e5
DEBUG:chess.engine:<UciProtocol (pid=1012)>: << go movetime 1000
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info string NNUE evaluation using source/engines/Windows/nn-82215d0fd0df.nnue enabled
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 1 seldepth 1 multipv 1 score cp 32 nodes 25695 nps 2141250 tbhits 0 time 12 pv g1f3
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 2 seldepth 2 multipv 1 score cp 20 nodes 26975 nps 2247916 tbhits 0 time 12 pv g1f3 b8c6
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 3 seldepth 3 multipv 1 score cp 20 nodes 27976 nps 2152000 tbhits 0 time 13 pv g1f3 b8c6 f1c4
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 4 seldepth 4 multipv 1 score cp 20 nodes 29051 nps 2234692 tbhits 0 time 13 pv g1f3 b8c6 f1c4 f8c5
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 5 seldepth 5 multipv 1 score cp 27 nodes 30112 nps 2150857 tbhits 0 time 14 pv g1f3 b8c6 f1c4 f8c5 e1g1
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 6 seldepth 6 multipv 1 score cp 21 nodes 31796 nps 2271142 tbhits 0 time 14 pv g1f3 b8c6 f1c4 f8c5 c2c3 g8f6
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 7 seldepth 7 multipv 1 score cp 20 nodes 33318 nps 2221200 tbhits 0 time 15 pv g1f3 b8c6 d2d4 e5d4 f3d4 g8f6 d4c6
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 8 seldepth 9 multipv 1 score cp 22 nodes 35755 nps 2383666 tbhits 0 time 15 pv g1f3 b8c6 f1c4 f8c5 c2c3 g8f6 d2d3 d7d6 b2b4
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 9 seldepth 11 multipv 1 score cp 21 nodes 38824 nps 2426500 tbhits 0 time 16 pv g1f3 b8c6 f1c4 f8c5 d2d3 d7d6 c2c3 g8f6 b2b4 c5b6 a2a4
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 10 seldepth 13 multipv 1 score cp 24 nodes 45821 nps 2411631 tbhits 0 time 19 pv g1f3 b8c6 d2d4 e5d4 f3d4 g8f6 d4c6 b7c6 b1c3 f8b4 d1d4 d8e7 e4e5
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 11 seldepth 17 multipv 1 score cp 29 nodes 52245 nps 2487857 tbhits 0 time 21 pv g1f3 b8c6 f1c4 f8c5 d2d3 d7d6 c2c3 g8f6 b2b4 c5b6 a2a4 a7a5 b4b5 c6e7
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 12 seldepth 14 multipv 1 score cp 30 nodes 54374 nps 2471545 tbhits 0 time 22 pv g1f3 b8c6 f1c4 f8c5 c2c3 g8f6 b2b4 c5b6 d2d3 d7d6 a2a4 a7a5 b4b5 c6e7
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 13 seldepth 20 multipv 1 score cp 34 nodes 62703 nps 2612625 tbhits 0 time 24 pv g1f3 b8c6 f1c4 f8c5 c2c3 g8f6 b2b4 c5b6 d2d3 d7d6 a2a4 a7a6 e1g1 e8g8 h2h3 c6e7 f1e1 b6a7
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 14 seldepth 22 multipv 1 score cp 20 nodes 88869 nps 2613794 tbhits 0 time 34 pv g1f3 b8c6 f1c4 f8c5 d2d3 g8f6 c2c3 d7d6 b2b4 c5b6 a2a4 a7a5 b4b5 c6e7 b1d2 e7g6 e1g1
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 15 seldepth 26 multipv 1 score cp 26 nodes 127586 nps 2319745 tbhits 0 time 55 pv g1f3 b8c6 f1c4 f8c5 c2c3 g8f6 d2d4 e5d4 e4e5 d7d5 c4b5 f6e4 c3d4 c5b4 b1d2 e8g8 a2a3
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 16 seldepth 22 multipv 1 score cp 29 nodes 131446 nps 2389927 tbhits 0 time 55 pv g1f3 b8c6 f1c4 f8c5 c2c3 g8f6 d2d4 e5d4 e4e5 d7d5 c4b5 f6e4 c3d4 c5b4 b1d2 e8g8 a2a3 b4a5 b5c6 b7c6
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 17 seldepth 25 multipv 1 score cp 33 nodes 843074 nps 3054615 tbhits 0 time 276 pv g1f3 b8c6 f1c4 f8c5 c2c3 g8f6 b2b4 c5b6 d2d3 d7d6 a2a4 a7a6 e1g1 e8g8 h2h3 c6e7 a4a5 b6a7 c1g5
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 18 seldepth 22 multipv 1 score cp 33 nodes 857480 nps 3062428 tbhits 0 time 280 pv g1f3 b8c6 f1c4 f8c5 c2c3 g8f6 b2b4 c5b6 d2d3 d7d6 a2a4 a7a6 e1g1 e8g8 h2h3 c6e7 a4a5 b6a7 c1g5 g8h8 f1e1 e7g6
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 19 seldepth 22 multipv 1 score cp 29 nodes 1042795 nps 3103556 tbhits 0 time 336 pv g1f3 b8c6 f1c4 f8c5 c2c3 g8f6 b2b4 c5b6 d2d3 d7d6 a2a4 a7a6 e1g1 e8g8 a4a5 b6a7 c1e3 a7e3 f2e3 c8d7 b1d2 c6e7
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 20 seldepth 26 multipv 1 score cp 32 nodes 2103913 nps 3093989 tbhits 0 time 680 pv g1f3 b8c6 f1c4 f8c5 c2c3 g8f6 b2b4 c5b6 d2d3 d7d6 a2a4 a7a5 b4b5 c6e7 b1d2 e8g8 e1g1 e7g6 f1e1 c8e6 c4e6 f7e6 d3d4 h7h6 d2c4 b6a7
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> info depth 21 seldepth 26 multipv 1 score cp 32 nodes 3100095 nps 3096998 hashfull 14 tbhits 0 time 1001 pv g1f3 b8c6 f1c4 f8c5 c2c3 g8f6 b2b4 c5b6 d2d3 d7d6 a2a4 a7a5 b4b5 c6e7 b1d2 e8g8 e1g1 e7g6 f1e1 c8e6 c4e6 f7e6 d3d4 h7h6 d2c4 b6a7
DEBUG:chess.engine:<UciProtocol (pid=1012)>: >> bestmove g1f3 ponder b8c6
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1455, in _parse_uci_bestmove
    move = board.push_uci(tokens[0].lower())
  File "C:\Program Files\Python38\lib\site-packages\chess\__init__.py", line 2920, in push_uci
    move = self.parse_uci(uci)
  File "C:\Program Files\Python38\lib\site-packages\chess\__init__.py", line 2907, in parse_uci
    raise ValueError(f"illegal uci: {uci!r} in {self.fen()}")
ValueError: illegal uci: 'g1f3' in rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Boštjan\Desktop\Chess Fighter\source\window.py", line 694, in invoke
    result = self.engine.play(
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 2355, in play
    return future.result()
  File "C:\Program Files\Python38\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Program Files\Python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Program Files\Python38\lib\asyncio\tasks.py", line 491, in wait_for
    return fut.result()
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1284, in play
    return await self.communicate(UciPlayCommand)
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 736, in communicate
    return await command.result
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 947, in _line_received
    self.line_received(engine, line)
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1241, in line_received
    self._bestmove(engine, line.split(" ", 1)[1])
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1260, in _bestmove
    best = _parse_uci_bestmove(engine.board, arg)
  File "C:\Program Files\Python38\lib\site-packages\chess\engine.py", line 1457, in _parse_uci_bestmove
    raise EngineError(err)
chess.engine.EngineError: illegal uci: 'g1f3' in rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
```

**Comment by niklasf** [comment]
From reading your code it looks like you are creating boards with inconsistent state and history, i.e., the move stack does not match the position. I'd recommend not using internals like `_board_state()` and `restore()` at all, as I have done before: https://github.com/niklasf/python-chess/issues/616#issuecomment-682484075, https://github.com/niklasf/python-chess/issues/618#issuecomment-688492849.

**Comment by PedanticHacker** [comment]
Is there even any alternative to `_board_state()` and `restore()`?

**Comment by PedanticHacker** [comment]
No, I'll keep using `_board_state()` and `restore()`, because that's the simplest thing to restore a board to a particular position. Why don't you provide a simple function to restore a board? One would just pass it a move (a `chess.Move` object) and voila! Yes? No?

**Comment by niklasf** [comment]
This is not a matter of style. Using it as you do is simply incorrect, and one symptom among many is this issue. Up to you :shrug: 

---

`chess.Move` alone does not have enough information to construct a board state, let alone the history.

You're looking for a method to restore a board's state and history from a snapshot. But why replace every property of a board, when you can just assign a new board?

```python
snapshot = self.board.copy()

# Some time later:
self.board = snapshot.copy()
```

Now you just need to maintain a list of these snapshots or use a data structure like `chess.pgn.Game` (https://github.com/niklasf/python-chess/issues/618#issuecomment-688492849).

**Comment by PedanticHacker** [comment]
@niklasf, I know that you are a busy man, but please answer me this. Are you saying that instead of `board = chess.Board()` I must use `game = chess.pgn.Game()` instead?

If you find the time, I am accepting PR requests for my [ChessFighter repo](https://github.com/PedanticHacker/ChessFighter). It would be nice to see how **you** would implement that. I am still learning, so your help would be a tremendeous boon.

**Comment by niklasf** [comment]
Please don't expect me to do that. For some example code, check how https://github.com/H-a-y-k/hichesslib or http://johncheetham.com/projects/jcchess/ implement it.

(Neither of them uses `chess.pgn.Game`, which is btw. *not* a drop in replacement for `chess.Board`. I suppose a list is simpler anyway, if you don't need a tree of variations.)

**Comment by PedanticHacker** [comment]
So I have created a list of `GameNode` objects:
`[<GameNode at 0x2c6e3d489a0 (1. e4 ...)>, <GameNode at 0x2c6e3d48df0 (1... e5 ...)>, <GameNode at 0x2c6e586b0d0 (2. Nf3 ...)>, <GameNode at 0x2c6e586b0a0 (2... Nc6 ...)>]`

How exactly can I now display a certain chessboard position from that list of `GameNode` objects, say I want to display `<GameNode at 0x2c6e3d48df0 (1... e5 ...)>`? What's the code to do that? What functions/methods must I use? Would I be needing to create a visitor (not sure what exactly that is, but just a thought)? Is there anything I am missing in this whole concept?

**Comment by niklasf** [comment]
Use [`node.board()`](https://python-chess.readthedocs.io/en/latest/pgn.html#chess.pgn.GameNode.board).

**Comment by PedanticHacker** [comment]
Also, isn't my list of `GameNode` objects similar to a list of board state objects?
`[<chess._BoardState object at 0x000002C6E3D51400>, <chess._BoardState object at 0x000002C6E3D51BE0>, <chess._BoardState object at 0x000002C6E5822BB0>, <chess._BoardState object at 0x000002C6E5822DC0>]`

**Comment by PedanticHacker** [comment]
The only difference is, as far as I can discern, that every board state object has this very handy `restore()` function/method, and every `GameNode` object has **what**?

**Comment by PedanticHacker** [comment]
As a reflection to `chess._BoardState.restore()`, we need `GameNode.restore()`. Then I'll be a very happy man. :)

**Comment by PedanticHacker** [comment]
I just noticed this `setup()` method of `chess.pgn.Game()`. Is **this** what I need? Does this `setup()` method operate the same as `restore()` does in `chess._BoardState`?

**Comment by PedanticHacker** [comment]
> `chess.Move` alone does not have enough information to construct a board state, let alone the history.

What if we associate a move and a board state in a Python dictionary where the move would be the dictionary's key and the board state would be the dictionary's value?

Currently, we have a move stack, a simple Python list that stores moves (`chess.Move` objects). But alongside that (or perhaps even supersedingly), we could store "move state" objects (a Python dictionary of `chess.Move` objects where each such object stores a board state).

What do you think about this idea?
