### ISSUE TITLE
Question - Adding a variation

### ISSUE THREAD

**Issue by CoderAryanAnand** [niklasf/python-chess#668]
Hi Niklas,
I have got a question again. Currently, I'm trying to add a variation using this code:
`def get_eval(fen):
    """
    Gets the current evaluation of the position
    """
    board = chess.Board(fen)
    engine = chess.engine.SimpleEngine.popen_uci(engfile)
    info = engine.analyse(board, chess.engine.Limit(0.1))
    engine.quit()
    return int(str(info['score'])) / 100

def get_best_var(fen, uci=False):
    """
    Gets the best variation from uci in position
    """
    board = chess.Board(fen)
    engine = chess.engine.SimpleEngine.popen_uci(engfile)
    result = engine.analyse(board, chess.engine.Limit(time=0.1))
    engine.quit()
    if uci:
        return result['pv']
    else:
        return board.variation_san(result['pv'])

prev_eva = 0.00
        for move in pgn.mainline_moves():
            board.push(move)
            eva = get_eval(board.fen())
            if 0.15 < abs(prev_eva - eva) <= 0.3:  # Good move, but not the best
                board.pop()
                pgn.add_line(get_best_var(board.fen(), uci=True),
                             starting_comment='Good move, but better was: ',
                             comment=str(get_eval(board.fen()))
                             )
                board.push(move)
            prev_eva = eva`

So that is my code until now(there are more than just good move, but it would have been a lot of code to add), but when the code runs, it only adds variations to move number 1 and sometimes the moves come as exe6, dxd4 and so forth. I think it might be happening while converting moves from UCI to SAN but I don't know. Could you please help me solve this problem?

Thanks again,
Aryan

**Comment by niklasf** [comment]
`pgn.add_line(...)` always adds to the root of the game. Instead do something like:

```python
for node in pgn.mainline():
   move = node.move
   # ...
   node.add_line(...)
```

A couple other recommendations:
* Keep a reference to a single `engine` instead of starting and terminating the engine over
* Check out the methods of [`chess.engine.PovScore`](https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.PovScore) for properly working with `info["score"]`. For example `info["score"].white().score(mate_score=10000)` gets an integer score, always from White's point of view, and does not break on mate score
* Engines are not perfect, so when using `abs(...)` you are also scolding the user for moves that are *better* than the engine initially thought

**Comment by CoderAryanAnand** [comment]
Hi Niklas,
Thank you for your response and recommendations.
This answers my question. 
Have a nice day!

**Comment by CoderAryanAnand** [comment]
Hi Niklas, I checked the code again which you sent me, and I have one more question. For some reason running that loop, 
board = pgn.board()
```
for node in pgn.mainline():
   move = node.move
   # ...
   node.add_line(get_best_var(board.fen(), True))
   board.push(move)
```
The game goes beyond the actual pgn. Why is that happening?

**Comment by niklasf** [comment]
Oh ... when doing `node.add_line()` on the final node of the game there is no alternative move. So the added line becomes the mainline, extending the game.

If the custom logic around `add_line()` does not prevent that, you could use `for node in list(pgn.mainline()): ...` to iterate over a snapshot of the mainline, instead of the extended one.

**Comment by CoderAryanAnand** [comment]
Hi Niklas,
Thanks for your response. Sorry for my late response.
When I run this code:
```
for node in list(pgn.mainline()):
   move = node.move
   # ...
   node.add_line(get_best_var(board.fen(), True))
   board.push(move)
```
and then 
`print(pgn)`
I get this error:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Aryan\anaconda3\envs\Chess-Graphical-Evaluation\lib\site-packages\chess\pgn.py", line 626, in __str__
    return self.accept(StringExporter(columns=None))
  File "C:\Users\Aryan\anaconda3\envs\Chess-Graphical-Evaluation\lib\site-packages\chess\pgn.py", line 706, in accept
    self.variations[0]._accept(board, visitor)
  File "C:\Users\Aryan\anaconda3\envs\Chess-Graphical-Evaluation\lib\site-packages\chess\pgn.py", line 562, in _accept
    top.node._accept_node(parent_board, visitor)
  File "C:\Users\Aryan\anaconda3\envs\Chess-Graphical-Evaluation\lib\site-packages\chess\pgn.py", line 539, in _accept_node
    visitor.visit_move(parent_board, self.move)
  File "C:\Users\Aryan\anaconda3\envs\Chess-Graphical-Evaluation\lib\site-packages\chess\pgn.py", line 1248, in visit_move
    self.write_token(board.san(move) + " ")
  File "C:\Users\Aryan\anaconda3\envs\Chess-Graphical-Evaluation\lib\site-packages\chess\__init__.py", line 2656, in san
    return self._algebraic(move)
  File "C:\Users\Aryan\anaconda3\envs\Chess-Graphical-Evaluation\lib\site-packages\chess\__init__.py", line 2669, in _algebraic
    san = self._algebraic_and_push(move, long=long)
  File "C:\Users\Aryan\anaconda3\envs\Chess-Graphical-Evaluation\lib\site-packages\chess\__init__.py", line 2674, in _algebraic_and_push
    san = self._algebraic_without_suffix(move, long=long)
  File "C:\Users\Aryan\anaconda3\envs\Chess-Graphical-Evaluation\lib\site-packages\chess\__init__.py", line 2710, in _algebraic_without_suffix
    assert piece_type, f"san() and lan() expect move to be legal or null, but got {move} in {self.fen()}"
AssertionError: san() and lan() expect move to be legal or null, but got e2e4 in rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
```
What does this mean?
This is the other code:

```
pgn = chess.pgn.read_game(open('new.pgn'))
board = pgn.board()
```

new.pgn:
```
[Event "It (cat.17)"]
[Site "Wijk aan Zee (Netherlands)"]
[Date "1999.??.??"]
[Round "?"]
[White "White player"]
[Black "Black player"]
[Result "1-0"]

1. e4 e5 2. d4 d5 3. Nc3 g6
```
How can I avoid this error?

**Comment by PedanticHacker** [comment]
> pgn = chess.pgn.read_game(open('new.pgn'))

I think this line is wrong. I think you don't need to use the Python's built-in function `open()`.

Try `pgn = chess.pgn.read_game('new.pgn')`.

**Comment by niklasf** [comment]
No, `open()` is definitely required, @PedanticHacker.

Based on the error you're adding analysis for the starting position to a node where `1. e4` has already been played. Maybe swap the order of `node.add_line(get_best_var(board.fen(), True))` and `board.push(move)`. If that doesn't work, please show the elided code for the full picture.

**Comment by CoderAryanAnand** [comment]
Hi Niklas, 
Thanks for your response. Now my code doesn't give an error. But it gives a different output than expected.
```
pgn = chess.pgn.read_game(open('new.pgn'))

def get_eval(fen):
    """
    Gets the current evaluation of the position
    """
    board = chess.Board(fen)
    engine = chess.engine.SimpleEngine.popen_uci(r'D:\stockfish_12\stockfish_20090216_x64_bmi2.exe')
    info = engine.analyse(board, chess.engine.Limit(0.1))
    engine.quit()
    return int(str(info['score'])) / 100

def get_best_var(fen, uci=False):
    """
    Gets the best variation from uci in position
    """
    board = chess.Board(fen)
    engine = chess.engine.SimpleEngine.popen_uci(r'D:\stockfish_12\stockfish_20090216_x64_bmi2.exe')
    result = engine.analyse(board, chess.engine.Limit(time=0.1))
    engine.quit()
    if uci:
        return result['pv']
    else:
        return board.variation_san(result['pv'])

board = pgn.board()

for node in list(pgn.mainline()):
    move = node.move
    # ...
    board.push(move)
    node.add_line(get_best_var(board.fen(), True))
print(pgn)
```
When I run this, I get:
```
[Event "It (cat.17)"]
[Site "Wijk aan Zee (Netherlands)"]
[Date "1999.??.??"]
[Round "?"]
[White "Garry Kasparov"]
[Black "Veselin Topalov"]
[Result "1-0"]
1. e4 e5 ( 1... e6 2. d4 ) 2. d4 ( 2. Nf3 Nf6 3. Nc3 Nc6 4. d4 exd4 5. Nxd4 Bb4 6. Nxc6 bxc6 7. Bd3 d5 8. exd5 cxd5 9. Qe2+ Be7 ) 2... d5 ( 2... exd4 ) 3. Nc3 ( 3. dxe5 Nc6 4. Qxd5 Qxd5 5. exd5 Nxe5 6. Nc3 Bf5 7. Bf4 Bd6 8. O-O-O O-O-O 9. Nf3 Nxf3 10. Bxd6 Rxd6 11. gxf3 Ne7 ) 3... g6 ( 3... dxe4 ) 4. exd5 exd4 1-0
```
But `new.pgn` is:
```
[Event "It (cat.17)"]
[Site "Wijk aan Zee (Netherlands)"]
[Date "1999.??.??"]
[Round "?"]
[White "White player"]
[Black "Black player"]
[Result "1-0"]

1. e4 e5 2. d4 d5 3. Nc3 g6
```
So it adds another move. Why does it do that?

**Comment by niklasf** [comment]
My guess is that this is the same issue as above:

> when doing node.add_line() on the final node of the game there is no alternative move. So the added line becomes the mainline, extending the game.

PGN does not have any other standard way of adding a variation to the last move. Perhaps doing `game.end().comment = "End of game"` before the loop might be reasonable solution.

**Comment by CoderAryanAnand** [comment]
Thanks Niklas. I'll use this idea.

**Comment by CoderAryanAnand** [comment]
> * Engines are not perfect, so when using `abs(...)` you are also scolding the user for moves that are _better_ than the engine initially thought.
What do you suggest I use?
