### ISSUE TITLE
Catching "ValueError"

### ISSUE THREAD

**Issue by Maxximiliann** [niklasf/python-chess#721]
```
import io
import chess.pgn

def main():
    raw_pgn = "1. Ne2 e6 2. d4 f6 3. e4 Kf7 4. Bd3 Nc6"
    pgn = io.StringIO(raw_pgn)

    try:
        chess.pgn.read_game(pgn)
    except:
        print("no bueno")
    else:
        print(raw_pgn)

if __name__ == '__main__':
    main()

```
```
$ python3 verify_pgn_prototype.py 
error during pgn parsing
Traceback (most recent call last):
  File "/home/maxximiliann/.local/lib/python3.8/site-packages/chess/pgn.py", line 1639, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "/home/maxximiliann/.local/lib/python3.8/site-packages/chess/pgn.py", line 1020, in parse_san
    return board.parse_san(san)
  File "/home/maxximiliann/.local/lib/python3.8/site-packages/chess/__init__.py", line 2990, in parse_san
    raise ValueError(f"illegal san: {san!r} in {self.fen()}")
ValueError: illegal san: 'Ne2' in rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
1. Ne2 e6 2. d4 f6 3. e4 Kf7 4. Bd3 Nc6
```
What's being called outside of the `except` block? Can't catch the `ValueError` exception. . .

**Comment by PedanticHacker** [comment]
It's generally not a good idea to catch a bare `except`, but to catch a specific exception, like `ValueError` in your case.

Please try `except ValueError`.

**Comment by niklasf** [comment]
No, the exception is not raised but logged, so that the parser can continue with the same game.

See the last few paragraphs of https://python-chess.readthedocs.io/en/latest/pgn.html#chess.pgn.read_game. The logger is `chess.pgn`, if you want to supress the output.
