### ISSUE TITLE
add support to run on top of trio

### ISSUE THREAD

**Issue by ZeeD** [niklasf/python-chess#725]
the [engine docs](https://python-chess.readthedocs.io/en/latest/engine.htm) says

> The preferred way to use the API is with an asyncio event loop. 

is there some way to run `python-chess` on top of [trio](https://github.com/python-trio/trio) event loop?

**Comment by niklasf** [comment]
Not directly, but the [trio-asyncio](https://github.com/python-trio/trio-asyncio) compatibility layer looks promising.

I can get

```python
import trio_asyncio
import chess.engine

async def main() -> None:
    transport, engine = await trio_asyncio.aio_as_trio(chess.engine.popen_uci)("/usr/bin/stockfish")

    result = await trio_asyncio.aio_as_trio(engine.play)(chess.Board(), chess.engine.Limit(time=0.1))
    print(result)

    await trio_asyncio.aio_as_trio(engine.quit)()

trio_asyncio.run(main)
```

to run with a small patch:

```diff
diff --git a/chess/engine.py b/chess/engine.py
index 2a02c7c..d970e9d 100644
--- a/chess/engine.py
+++ b/chess/engine.py
@@ -936,7 +936,7 @@ class Protocol(asyncio.SubprocessProtocol, metaclass=abc.ABCMeta):
     """Future: Exit code of the process."""

     def __init__(self: ProtocolT) -> None:
-        self.loop = asyncio.get_running_loop()
+        self.loop = asyncio.get_event_loop()
         self.transport: Optional[asyncio.SubprocessTransport] = None

         self.buffer = {
@@ -1195,7 +1195,7 @@ class Protocol(asyncio.SubprocessProtocol, metaclass=abc.ABCMeta):
                 popen_args["preexec_fn"] = os.setpgrp
         popen_args.update(kwargs)

-        return await asyncio.get_running_loop().subprocess_exec(cls, *command, **popen_args)  # type: ignore
+        return await asyncio.get_event_loop().subprocess_exec(cls, *command, **popen_args)  # type: ignore


 class CommandState(enum.Enum):
```

Somehow it does not appear to support `asyncio.get_running_loop()`, maybe due to https://github.com/python-trio/trio-asyncio/issues/83?

**Comment by niklasf** [comment]
`asyncio.get_running_loop()` -> `asyncio.events.get_running_loop()` is a better workaround. Comitted that to master, so trio-asyncio is working with it, now.

**Comment by ZeeD** [comment]
Sorry, but I still have errors running your snippet:

I'm using python 3.8,  trio 0.17.0, trio-asyncio 0.11.0 and chess  1.3.3 using `setup.py` with `chess @ git+https://github.com/niklasf/python-chess#egg=chess` as dependency 

```
C:\Users\vito.detullio\Desktop\workspace-mystuff\moves_VENV\lib\site-packages\trio_asyncio\_base.py:20: TrioDeprecationWarning: trio.hazmat is deprecated since Trio 0.15.0; use trio.lowlevel instead (https://github.com/python-trio/trio/issues/476)
  from trio.hazmat import wait_for_child
Traceback (most recent call last):
  File "C:\Users\vito.detullio\Desktop\workspace-mystuff\moves\_dbg\demo.py", line 14, in <module>
    trio_asyncio.run(main)
  File "C:\Users\vito.detullio\Desktop\workspace-mystuff\moves_VENV\lib\site-packages\trio_asyncio\_loop.py", line 429, in run
    return trio.run(_run_task, proc, args)
  File "C:\Users\vito.detullio\Desktop\workspace-mystuff\moves_VENV\lib\site-packages\trio\_core\_run.py", line 1928, in run
    raise runner.main_task_outcome.error
  File "C:\Users\vito.detullio\Desktop\workspace-mystuff\moves_VENV\lib\site-packages\trio_asyncio\_loop.py", line 427, in _run_task
    return await proc(*args)
  File "C:\Users\vito.detullio\Desktop\workspace-mystuff\moves\_dbg\demo.py", line 7, in main
    transport, engine = await trio_asyncio.aio_as_trio(chess.engine.popen_uci)(moves.configurations.local.STOCKFISH)
  File "C:\Users\vito.detullio\Desktop\workspace-mystuff\moves_VENV\lib\site-packages\trio_asyncio\_adapter.py", line 56, in __call__
    return await self.loop.run_aio_coroutine(f)
  File "C:\Users\vito.detullio\Desktop\workspace-mystuff\moves_VENV\lib\site-packages\trio_asyncio\_base.py", line 240, in run_aio_coroutine
    return await run_aio_future(fut)
  File "C:\Users\vito.detullio\Desktop\workspace-mystuff\moves_VENV\lib\site-packages\trio_asyncio\_util.py", line 45, in run_aio_future
    res = await trio.hazmat.wait_task_rescheduled(abort_cb)
  File "C:\Users\vito.detullio\Desktop\workspace-mystuff\moves_VENV\lib\site-packages\trio\_core\_traps.py", line 166, in wait_task_rescheduled
    return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
  File "C:\Users\vito.detullio\Desktop\workspace-mystuff\moves_VENV\lib\site-packages\outcome\_impl.py", line 138, in unwrap
    raise captured_error
  File "C:\Users\vito.detullio\Desktop\workspace-mystuff\moves_VENV\lib\site-packages\trio_asyncio\_adapter.py", line 19, in _call_defer
    return await proc(*args, **kwargs)
  File "C:\Users\vito.detullio\Desktop\workspace-mystuff\moves_VENV\lib\site-packages\chess\engine.py", line 2573, in popen_uci
    transport, protocol = await UciProtocol.popen(command, setpgrp=setpgrp, **popen_args)
  File "C:\Users\vito.detullio\Desktop\workspace-mystuff\moves_VENV\lib\site-packages\chess\engine.py", line 1198, in popen
    return await asyncio.events.get_running_loop().subprocess_exec(cls, *command, **popen_args)  # type: ignore
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1615, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 487, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
```

**Comment by ZeeD** [comment]
Sorry to make you reopen the bug, I think the underlying cause is python-trio/trio-asyncio#97 (and the fact that I'm using a windows machine)

**Comment by PedanticHacker** [comment]
Maybe wait until chess v1.3.4? Because chess v1.3.3 does not include the trio-asyncio fix that Niklas has commited to the master branch. Just my 2 cents.

But if you have manually edited your chess v1.3.3 codebase with the fix that Niklas has provided, then we have an unsolved issue.

**Comment by ZeeD** [comment]
@PedanticHacker I am using master: 

> chess @ git+https://github.com/niklasf/python-chess#egg=chess

FWIW the demo code seems to work on WSL

**Comment by PedanticHacker** [comment]
This is clearly out of my expertise. Just wait some time, Niklas will respond.

**Comment by niklasf** [comment]
@PedanticHacker Have you received my email (end of December)? I was asking you to hold back on communication when you are unsure about an issue, to avoid needless notifications. Final warning.

**Comment by niklasf** [comment]
Alright, trio-asyncio v0.12.0 (just released) includes the proper fix, so I reverted the workaround. Subprocess support is still missing on Windows, but there's not much that could be done in python-chess, so closing.
