### ISSUE TITLE
ChestUCI does not work

### ISSUE THREAD

**Issue by ipostr08** [niklasf/python-chess#726]
import chess
import chess.engine
engineChest = chess.engine.SimpleEngine.popen_uci("u:/chestuci/chestUCI.exe")

```
Exception in callback Protocol.pipe_data_received(1, b'id author F...true\nuciok\n')
handle: <Handle Protocol.pipe_data_received(1, b'id author F...true\nuciok\n')>
Traceback (most recent call last):
  File "C:\anaconda3\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\anaconda3\lib\site-packages\chess\engine.py", line 976, in pipe_data_received
    line = line_bytes.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 47: invalid start byte
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
<ipython-input-7-aa5d27b5659c> in <module>
      1 import chess
      2 import chess.engine
----> 3 engineChest = chess.engine.SimpleEngine.popen_uci("u:/chestuci/chestUCI.exe")

C:\anaconda3\lib\site-packages\chess\engine.py in popen_uci(cls, command, timeout, debug, setpgrp, **popen_args)
   2734         Returns a :class:`~chess.engine.SimpleEngine` instance.
   2735         """
-> 2736         return cls.popen(UciProtocol, command, timeout=timeout, debug=debug, setpgrp=setpgrp, **popen_args)
   2737 
   2738     @classmethod

C:\anaconda3\lib\site-packages\chess\engine.py in popen(cls, Protocol, command, timeout, debug, setpgrp, **popen_args)
   2726             await simple_engine.shutdown_event.wait()
   2727 
-> 2728         return run_in_background(background, name=f"{cls.__name__} (command={command!r})", debug=debug)
   2729 
   2730     @classmethod

C:\anaconda3\lib\site-packages\chess\engine.py in run_in_background(coroutine, name, debug, _policy_lock)
    198 
    199     threading.Thread(target=background, name=name).start()
--> 200     return future.result()
    201 
    202 

C:\anaconda3\lib\concurrent\futures\_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

C:\anaconda3\lib\concurrent\futures\_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

C:\anaconda3\lib\site-packages\chess\engine.py in background()
    192     def background() -> None:
    193         try:
--> 194             asyncio.run(coroutine(future))
    195             future.cancel()
    196         except Exception as exc:

C:\anaconda3\lib\asyncio\runners.py in run(main, debug)
     41         events.set_event_loop(loop)
     42         loop.set_debug(debug)
---> 43         return loop.run_until_complete(main)
     44     finally:
     45         try:

C:\anaconda3\lib\asyncio\base_events.py in run_until_complete(self, future)
    614             raise RuntimeError('Event loop stopped before Future completed.')
    615 
--> 616         return future.result()
    617 
    618     def stop(self):

C:\anaconda3\lib\site-packages\chess\engine.py in background(future)
   2718             simple_engine = cls(transport, protocol, timeout=timeout)
   2719             try:
-> 2720                 await asyncio.wait_for(protocol.initialize(), timeout)
   2721                 future.set_result(simple_engine)
   2722                 returncode = await protocol.returncode

C:\anaconda3\lib\asyncio\tasks.py in wait_for(fut, timeout, loop)
    488             # See https://bugs.python.org/issue32751
    489             await _cancel_and_wait(fut, loop=loop)
--> 490             raise exceptions.TimeoutError()
    491     finally:
    492         timeout_handle.cancel()

TimeoutError: 
```

With logging:

```
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:chess.engine:<UciProtocol (pid=27484)>: Connection made
DEBUG:chess.engine:<UciProtocol (pid=27484)>: << uci
ERROR:asyncio:Exception in callback Protocol.pipe_data_received(1, b'id author F...default -rS\n')
handle: <Handle Protocol.pipe_data_received(1, b'id author F...default -rS\n')>
Traceback (most recent call last):
  File "C:\anaconda3\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\anaconda3\lib\site-packages\chess\engine.py", line 976, in pipe_data_received
    line = line_bytes.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 47: invalid start byte
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> id name ChestUCI Ver.5.2
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> id author Franz Huber
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name HashSize type spin default 64 min -1 max 2048
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name DefenderMoves type check default false
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name SearchDepth type spin default 10 min 0 max 126
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name AllSolutions type check default true
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name FullMovelist type check default true
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name CompleteDuals type check default false
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name UseDatabase type check default true
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name SearchMode type combo default Normal var Normal var Special var Automatic var AutoTurbo var RetroAnalysis var ParameterAnalysis var DatabaseAnalysis var EgtbAnalysis
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name ChecksOnly type spin default 0 min -1 max 31
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name ThreatDepth type spin default 0 min -125 max 125
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name ThreatRange type string default 3
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name KingSquares type spin default 0 min -9 max 9
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name PieceLimit type spin default 0 min -16 max 16
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name MaxMoves type spin default 0 min -222 max 222
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name SearchOrder type combo default KPX var KPX var KXP var PKX var PXK var XKP var XPK var only_CR var only_CRK
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name RetroOptions type spin default 7 min 0 max 7
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name EgtbCache type spin default 16 min 1 max 1024
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name EgtbPath type string default 
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name ShowAnalysis type check default true
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name ShowProgress type check default true
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name ShowStatistics type check default false
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name EngineMode type combo default UCI var UCI var Chest var Expert
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name ExpertOptions type string default -rS
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name Show Options type button
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name AutoClipboard type check default true
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name AutoLogfile type check default false
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name Show Logfile type button
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name AutoSolution type check default false
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name Show Solution type button
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name TextViewer type string default 
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name CpuInfo type string default 
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> option name German type check default true
DEBUG:chess.engine:<UciProtocol (pid=27484)>: >> uciok
```

**Comment by niklasf** [comment]
Thanks for reporting. I added some error handling / debugging to current master. Can you please update and make a new debug log with that version?

**Comment by ipostr08** [comment]
```
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:chess.engine:<UciProtocol (pid=35560)>: Connection made
DEBUG:chess.engine:<UciProtocol (pid=35560)>: << uci
WARNING:chess.engine:<UciProtocol (pid=35560)>: >> b'option name ProblemType type combo default Mate\xb7 var Mate\xb7 var Stalemate var SelfMate var SelfStalemate var HelpMate var HelpStalemate' ('utf-8' codec can't decode byte 0xb7 in position 47: invalid start byte)
DEBUG:chess.engine:<UciProtocol (pid=35560)>: >> id name ChestUCI Ver.5.2
DEBUG:chess.engine:<UciProtocol (pid=35560)>: >> id author Franz Huber

```

**Comment by niklasf** [comment]
Alright, thanks. Loooks like this is arguably a bug in ChestUCI by providing an option value `Mate·` (with the wierd dot) encoded in latin-1, while the conservative thing to do would be using ASCII only, since the UCI protocol specifies text but no particular encoding.

The latest version will now just ignore that option and continue.
