### ISSUE TITLE
Unexpected crash after queen is lost.

### ISSUE THREAD

**Issue by richardmcameron** [niklasf/python-chess#756]
Engine plays fine up until queen is lost on any board. Using most recent version of stockfish and python-chess.

```
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\chess-bot-2\main.py", line 90, in <module>
    result = engine.play(board, limit)
  File "C:\Users\User\PycharmProjects\chess-bot-2\venv\lib\site-packages\chess\engine.py", line 2689, in play
    return future.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 440, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "C:\Users\User\PycharmProjects\chess-bot-2\venv\lib\site-packages\chess\engine.py", line 1602, in play
    return await self.communicate(UciPlayCommand)
  File "C:\Users\User\PycharmProjects\chess-bot-2\venv\lib\site-packages\chess\engine.py", line 1053, in communicate
    return await command.result
chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 3221225477)
```

**Comment by niklasf** [comment]
Hi. Please also provide the debug log (https://python-chess.readthedocs.io/en/latest/engine.html#logging).
