### ISSUE TITLE
simpleEngine hits illegal move while analyse method is called

### ISSUE THREAD

**Issue by konqr** [niklasf/python-chess#764]
```
Exception parsing pv from info: 'depth 17 seldepth 25 multipv 1 score cp 45 nodes 255537 nps 1101452 tbhits 0 time 232 pv d2d4 d7d5 c1h6 c8h3 g2h3 g7h6 e2e3 c7c6 c2c4 e7e6 b1c3 d8b6 a1b1 b8d7 c4d5 e6d5 f1d3 e8c8 e1g1 c8b8', position at root: r1bqk2r/6b1/PpPpPpPp/8/8/7N/PPPPPPPP/RNBQKB1R w KQkq - 9 16
Exception parsing pv from info: 'depth 18 seldepth 25 multipv 1 score cp 43 nodes 363546 nps 1146832 tbhits 0 time 317 pv d2d4 g7g6 d4d5 f8g7 e2e4 c7c6 c2c4 d7d6 h3f4 e7e5 f4d3 c6d5 c4d5 f7f5 b1c3 e8g8 f1e2', position at root: r1bqk2r/6b1/PpPpPpPp/8/8/7N/PPPPPPPP/RNBQKB1R w KQkq - 9 16
Exception parsing pv from info: 'depth 19 seldepth 21 multipv 1 score cp 43 nodes 436811 nps 1146485 tbhits 0 time 381 pv d2d4 g7g6 d4d5 f8g7 e2e4 c7c6 c2c4 d7d6 h3g5 d8b6 d1d2 c6d5 c4d5 h6g4 b1c3 e8g8 h2h3 g4f6 f1e2 b8d7', position at root: r1bqk2r/6b1/PpPpPpPp/8/8/7N/PPPPPPPP/RNBQKB1R w KQkq - 9 16
Exception parsing pv from info: 'depth 20 seldepth 28 multipv 1 score cp 49 nodes 668062 nps 1169985 tbhits 0 time 571 pv d2d4 d7d5 c1h6 c8h3 g2h3 g7h6 e2e3 c7c6 c2c4 e7e6 b1c3 b8d7 c4d5 c6d5 f1d3 a7a6 e1g1 d8g5 g1h1 h8g8 f1g1 g5g1 d1g1 g8g1 a1g1 a8b8 d3h7', position at root: r1bqk2r/6b1/PpPpPpPp/8/8/7N/PPPPPPPP/RNBQKB1R w KQkq - 9 16
Exception parsing pv from info: 'depth 21 seldepth 30 multipv 1 score cp 40 nodes 1208684 nps 1207476 hashfull 536 tbhits 0 time 1001 pv d2d4 g7g6', position at root: r1bqk2r/6b1/PpPpPpPp/8/8/7N/PPPPPPPP/RNBQKB1R w KQkq - 9 16
Engine sent invalid ponder move
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/chess/engine.py", line 1760, in _parse_uci_bestmove
    ponder = board.parse_uci(tokens[2].lower())
  File "/usr/local/lib/python3.7/dist-packages/chess/__init__.py", line 3035, in parse_uci
    raise ValueError(f"illegal uci: {uci!r} in {self.fen()}")
ValueError: illegal uci: 'g7g6' in r1bqk2r/6b1/PpPpPpPp/8/3P4/7N/PPP1PPPP/RNBQKB1R b KQkq - 0 16
```

**Comment by niklasf** [comment]
Is https://lichess.org/analysis/standard/r1bqk2r/6b1/PpPpPpPp/8/8/7N/PPPPPPPP/RNBQKB1R_w_KQkq_-_9_16 the position you are analysing?

If so, this is a bug in the engine, not this library, since after `d2d4` the move `d7d5` is not legal.

Note that not all engines are designed to handle impossible material combinations:

```python
>>> import chess
>>> board = chess.Board("r1bqk2r/6b1/PpPpPpPp/8/8/7N/PPPPPPPP/RNBQKB1R w KQkq - 9 16")
>>> board.status()
<Status.TOO_MANY_WHITE_PIECES|TOO_MANY_WHITE_PAWNS: 72>
>>> board.is_valid()
False
```

**Comment by konqr** [comment]
Firstly thanks a lot for the extremely quick reply.
Understood, I am closing this question now.
