### ISSUE TITLE
import chess fails with python 3

### ISSUE THREAD

**Issue by lucasart** [niklasf/python-chess#78]
**Python 2**
```
$ python
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import chess
>>>
```
**Pyhton 3**
```
$ python3
Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chess
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'chess'
```
I just installed the library, using pip: `sudo pip install python-chess`. Is there anything special to do to make it work in Python 3 ?

**Comment by jackalsh** [comment]
Please make sure you use pip for python 3.

**Comment by niklasf** [comment]
Maybe your operating system has a seperate `pip3`.

**Comment by lucasart** [comment]
Thanks guys. Problem solved, as follows (on lubuntu 15.10):
```
sudo apt-get install python3-pip
sudo pip3 install python-chess
```

**Comment by stevexyz** [comment]
For the records I solved with:
sudo -H pip3 uninstall python-chess
sudo -H pip3 install python-chess

**Comment by fafamonge** [comment]
I'm stuck with this installation. A lot of problems and now getting this:

```
rafael@ProBook:/usr/share/lucaschess/Linux$ ./xlucas.sh 
x86_64
Traceback (most recent call last):
  File "./Lucas.py", line 47, in <module>
    import Code.Init
  File "./Code/Init.py", line 5, in <module>
    from Code import Procesador
  File "./Code/Procesador.py", line 30, in <module>
    from Code import GestorRoutes
  File "./Code/GestorRoutes.py", line 11, in <module>
    from Code import LibChess
  File "./Code/LibChess.py", line 4, in <module>
    import chess
ImportError: No module named chess
```
My Python and PIP version:
```
rafael@ProBook:/usr/share/lucaschess/Linux$ pip --version
pip 19.1.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
```
All modules and dependencies are installed:
```
rafael@ProBook:/usr/share/lucaschess/Linux$ pip freeze
apt-clone==0.2.1
apturl==0.5.2
beautifulsoup4==4.6.0
Brlapi==0.6.6
certifi==2018.1.18
chardet==3.0.4
command-not-found==0.3
configobj==5.0.6
cupshelpers==1.0
Cython==0.29.9
defer==1.0.6
httplib2==0.9.2
idna==2.6
louis==3.5.0
macaroonbakery==1.1.3
Mako==1.0.7
MarkupSafe==1.0
nemo-emblems==4.0.2
netifaces==0.10.4
onboard==1.4.1
PAM==0.4.2
pexpect==4.2.1
Photohash==0.4.1
Pillow==5.1.0
protobuf==3.0.0
psutil==5.4.2
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.1
pygobject==3.26.1
PyICU==1.9.8
pyinotify==0.9.6
pymacaroons==0.13.0
PyNaCl==1.1.2
pyRFC3339==1.0
python-apt==1.6.4
python-chess==0.28.0
python-debian==0.1.32
python-xapp==1.4.0
python-xlib==0.20
pytz==2018.3
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
requests==2.18.4
requests-unixsocket==0.1.5
scandir==1.10.0
sessioninstaller==0.0.0
setproctitle==1.1.10
six==1.11.0
system-service==0.3
systemd-python==234
ubuntu-drivers-common==0.0.0
ufw==0.36
urllib3==1.22
xkit==0.0.0
```
I'm running Linux Mint 19.1 Cinnamon
