### ISSUE TITLE
ValueError: illegal uci

### ISSUE THREAD

**Issue by ScarecrowY** [niklasf/python-chess#800]
Hi, I am encountering the below ValueError. I think it's because the current board state is invalid for the move, but I just want to eliminate the possibility that the move 'a7a8q' is not right. Are we able to pass in the promotion option following the move?

```
Traceback (most recent call last):
  File "/var/www/Human_Trust/venv/lib/python3.6/site-packages/chess/engine.py", line 1486, in _parse_uci_bestmove
    move = board.push_uci(tokens[0].lower())
  File "/var/www/Human_Trust/venv/lib/python3.6/site-packages/chess/__init__.py", line 2896, in push_uci
    move = self.parse_uci(uci)
  File "/var/www/Human_Trust/venv/lib/python3.6/site-packages/chess/__init__.py", line 2883, in parse_uci
    raise ValueError(f"illegal uci: {uci!r} in {self.fen()}")
ValueError: illegal uci: 'a7a8q' in P7/2k5/6r1/5p2/PR5P/1KP5/8/8 b - - 0 46

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/Human_Trust/UCI_interface/calculate_move.py", line 29, in next_move
    opponent_result = engine.play(threat_board, chess.engine.Limit(time=2), options={'UCI_LimitStrength': True, 'UCI_Elo': agent_elo})
  File "/var/www/Human_Trust/venv/lib/python3.6/site-packages/chess/engine.py", line 2386, in play
    return future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/var/www/Human_Trust/venv/lib/python3.6/site-packages/chess/engine.py", line 1316, in play
    return await self.communicate(UciPlayCommand)
  File "/var/www/Human_Trust/venv/lib/python3.6/site-packages/chess/engine.py", line 768, in communicate
    return await command.result
  File "/var/www/Human_Trust/venv/lib/python3.6/site-packages/chess/engine.py", line 979, in _line_received
    self.line_received(engine, line)
  File "/var/www/Human_Trust/venv/lib/python3.6/site-packages/chess/engine.py", line 1273, in line_received
    self._bestmove(engine, line.split(" ", 1)[1])
  File "/var/www/Human_Trust/venv/lib/python3.6/site-packages/chess/engine.py", line 1292, in _bestmove
    best = _parse_uci_bestmove(engine.board, arg)
  File "/var/www/Human_Trust/venv/lib/python3.6/site-packages/chess/engine.py", line 1488, in _parse_uci_bestmove
    raise EngineError(err)
chess.engine.EngineError: illegal uci: 'a7a8q' in P7/2k5/6r1/5p2/PR5P/1KP5/8/8 b - - 0 46
```

**Comment by niklasf** [comment]
The notation would be correct for queen promotion, but in https://lichess.org/analysis/standard/P7/2k5/6r1/5p2/PR5P/1KP5/8/8_b_-_-_0_46 the pawn is not yet on a7.
