### ISSUE TITLE
0readyok?

### ISSUE THREAD

**Issue by djdekker** [niklasf/python-chess#83]
While playing with PicoChess (on Raspbian Jessie with python-chess updated to 0.14.1) against Floyd 0.8 by @kervinck I encountered the following error:

2016-06-19 17:20:23.471 ERROR        uci - handle_integer_token: exception parsing integer token
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 678, in handle_integer_token
    intval = int(token)
ValueError: invalid literal for int() with base 10: '0readyok'

Somehow a zero got inserted before the 'readyok' message and the game stalled.

Is this a python-chess issue or is it rather engine related?

**Comment by kervinck** [comment]
My thinking is the following:

In floyd 0.8 the only place the ‘0’ can possibly come from is the info strings written during search. The search is running in a child process different from the uci parsing main process.
Normally these info strings are followed by a flush of the output buffer provided by the C library. However there is one condition where the flush is postponed, and that is in the first 0.1 seconds of search.

In any case, the end of a search is indicated with a 'bestmove’ line, which is always followed by a flush in floyd. So even info strings written in the first 0.1 seconds will be flushed. After ‘bestmove’, floyd won’t write anything unless asked for.

So from my point of view (and with the limited information I have), this ‘0readyok’ can happen when the uci-host (python-chess) sends a ‘isready’ command to the engine while it is thinking. In this case very quickly after starting a search.

If that is indeed the case, I believe python-chess is at fault, as when an UCI engine is thinking the UCI host can only wait for the move to complete, or stop the search with ‘stop’ before sending anything else. (The only other valid command is ‘ponderhit’, but after that it still can’t send ‘isready’)

Full logging needs to confirm, but I suspect floyd is ok here.

If lfoyd is in the wrong, I have to consider fixes or workarounds:
1. I could add extra flush commands in the first 0.1 seconds, but that would cost a bit of elo in very fast games.
2. Another workaround could be to add an extra newline before ‘readyok’. But there is clearly some garbage in the output buffer.
3. A third possibility is to let any unexpected command stop the search, or at least ‘isready’.
I’m hesitant to proceed with any of the three until I better understand the issue.

Marcel

**Comment by kervinck** [comment]
I just realised that even additional flushing wouldn't necessarily workaround the problem. Anytime there is an 'isready' coming in at the same time an info string is being composed, the output of both processes can become intermingled. It can be dependent on the platform and buffer size if the issue then shows as mangled output or not.

I'm running the FICS version of floyd on a rpi/arm32 + polyglot 24/7, with pondering on, and as far as I know that combination doesn't suffer from this type of hangup.

Reading the UCI specs however I notice this:
"This command must always be answered with "readyok" and can be sent also when the engine is calculating in which case the engine should also immediately answer with "readyok" without stopping the search."

So I don't know what the other interfaces do, but this indicates that I need to make floyd robust against this scenario anyway. It isn't easy because of the buffer issue. A synchronisation primitive will be needed. I will put it on the list for version 0.9.

**Comment by djdekker** [comment]
Here's part of the picochess.log from another game, not showing **0readyok** but **37212readyok**:

2016-06-19 20:46:08.920 DEBUG  dgtserial - process_board_message: 
r....rk.
..pqppbp
......p.
.p.p....
pP.PnP..
..PbPRP.
P.NB..BP
R..Q..K.
2016-06-19 20:46:08.925 DEBUG  picochess - main: received event from evt_queue: EVT_USER_MOVE
2016-06-19 20:46:08.926 DEBUG  dgtserial - process_board_message: Raw-Fen [r4rk1/2pqppbp/6p1/1p1p4/pP1PnP2/2PbPRP1/P1NB2BP/R2Q2K1]
2016-06-19 20:46:08.927 DEBUG  picochess - main: user move [f2f3]
2016-06-19 20:46:08.929 DEBUG dgtdisplay - run: received message from msg_queue: MSG_DGT_FEN
2016-06-19 20:46:08.944 DEBUG dgtdisplay - run: DGT-Fen: r4rk1/2pqppbp/6p1/1p1p4/pP1PnP2/2PbPRP1/P1NB2BP/R2Q2K1
2016-06-19 20:46:08.950 DEBUG dgtdisplay - run: ignore same fen
2016-06-19 20:46:08.957 DEBUG dgtdisplay - run: received message from msg_queue: MSG_CLOCK_STOP
2016-06-19 20:46:08.963 DEBUG dgtdisplay - run: received message from msg_queue: MSG_USER_MOVE
2016-06-19 20:46:08.970 DEBUG dgtdisplay - run: received message from msg_queue: MSG_CLOCK_START
2016-06-19 20:46:08.971 DEBUG   dgtiface - run: received command from dgt_queue: DGT_CLOCK_STOP
2016-06-19 20:46:09.083 DEBUG   dgtiface - run: max timer not running
2016-06-19 20:46:09.094 DEBUG   dgtiface - process_message: handle DgtApi: DGT_CLOCK_STOP
2016-06-19 20:46:09.100 DEBUG  dgtserial - write_board_command: ->DGT board [DgtClk.DGT_CMD_CLOCK_SETNRUN], length: 12
2016-06-19 20:46:09.116 DEBUG  dgtserial - write_board_command: DGT clock [ser]: locked
2016-06-19 20:46:09.117 DEBUG   dgtiface - run: received command from dgt_queue: DGT_CLOCK_START
2016-06-19 20:46:09.117 DEBUG  picochess - main: received event from evt_queue: EVT_DGT_CLOCK_CALLBACK
2016-06-19 20:46:09.118 DEBUG   dgtiface - run: max timer not running
2016-06-19 20:46:09.128 DEBUG  picochess - main: callback started <function main.<locals>.tc_stop_callback at 0x74fd58a0>
2016-06-19 20:46:09.139 DEBUG  dgtserial - write_board_command: ->DGT board [DgtCmd.DGT_RETURN_SERIALNR], length: 1
2016-06-19 20:46:09.139 DEBUG   dgtiface - process_message: handle DgtApi: DGT_CLOCK_START
2016-06-19 20:46:09.145 DEBUG  dgtserial - read_board_message: <-DGT board [DgtMsg.DGT_MSG_BWTIME], length: 7
2016-06-19 20:46:09.147  INFO  dgtserial - process_board_message: DGT clock [ser]: received time from clock l:[0, 0, 18] r:[0, 0, 40]
2016-06-19 20:46:09.147 DEBUG   dgtiface - process_message: last time received from clock l:(0, 0, 18) r:(0, 0, 40)
2016-06-19 20:46:09.148 DEBUG  dgtserial - process_board_message: DGT clock [ser]: unlocked after 0.031 secs
2016-06-19 20:46:09.145  INFO timecontrol - stop: old internal time w:(0, 0, 18) b:(0, 0, 40)
2016-06-19 20:46:09.149 DEBUG   dgtiface - process_message: sending time to clock l:(0, 0, 18) r:(0, 0, 40)
2016-06-19 20:46:09.149 DEBUG dgtdisplay - run: received message from msg_queue: MSG_DGT_CLOCK_TIME
2016-06-19 20:46:09.150  INFO timecontrol - stop: used time: 0.8 secs
2016-06-19 20:46:09.151 DEBUG  dgtserial - write_board_command: ->DGT board [DgtClk.DGT_CMD_CLOCK_SETNRUN], length: 12
2016-06-19 20:46:09.152  INFO timecontrol - stop: new internal time w:(0, 0, 18) b:(0, 0, 40)
2016-06-19 20:46:09.153 DEBUG  dgtserial - write_board_command: DGT clock [ser]: locked
2016-06-19 20:46:09.153 DEBUG  picochess - main: callback ended <function main.<locals>.tc_stop_callback at 0x74fd58a0>
2016-06-19 20:46:09.154 DEBUG   dgtiface - run: received command from dgt_queue: DGT_CLOCK_TIME
2016-06-19 20:46:09.154 DEBUG  picochess - main: received event from evt_queue: EVT_DGT_CLOCK_CALLBACK
2016-06-19 20:46:09.155 DEBUG   dgtiface - run: max timer not running
2016-06-19 20:46:09.155 DEBUG  picochess - main: callback started <function main.<locals>.think_callback at 0x74fd55d0>
2016-06-19 20:46:09.156 DEBUG   dgtiface - process_message: handle DgtApi: DGT_CLOCK_TIME
2016-06-19 20:46:09.156  INFO timecontrol - start: start internal time w:(0, 0, 18) - b:(0, 0, 40)
2016-06-19 20:46:09.182 DEBUG  picochess - main: callback ended <function main.<locals>.think_callback at 0x74fd55d0>
2016-06-19 20:46:09.183 DEBUG dgtdisplay - run: received message from msg_queue: MSG_SEARCH_STARTED
2016-06-19 20:46:09.185 ERROR        uci - handle_integer_token: exception parsing integer token
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/chess/uci.py", line 678, in handle_integer_token
    intval = int(token)
ValueError: invalid literal for int() with base 10: '37212readyok'

**Comment by djdekker** [comment]
A log of a complete game until the error (this time **13487readyok**) is here: http://pastebin.com/ya9biSE8

**Comment by kervinck** [comment]
Hi DJ, 

I have convinced myself that I can make an simple, albeit somewhat ugly, fix in floyd 0.8 to get picochess+python-chess working with floyd 0.8.
The idea is that I will let floyd print ‘\nreadyok\n in response to ‘isready’ (so inserting an additional newline).
This should then always work, because stdio functions are thread-safe otherwise.
I will release this as a floyd 0.8.1 version, in principle for arm32 first. Maybe for other platforms later if successful.
Hopefully today. I have to learn some additional git commands to do this :-)

Marcel

**Comment by kervinck** [comment]
Hello Dirk-Jan,

I have created a patched version of Floyd 0.8, dubbed 0.8.1 with a very simple workaround in it. Could you test it?

Change / source:
https://github.com/kervinck/floyd/commit/275f67f4404831841fe9a3c22629044b271599ac

Binary (arm32 only):
https://marcelk.net/floyd/floyd0.8.1.linux <https://marcelk.net/floyd/floyd0.8.1.linux>.arm32

Completely untested, but the change is very small.

Marcel

**Comment by djdekker** [comment]
Wow thanks for your fast patch Marcel!! I have just compiled Floyd 0.8.1 from source on my RPi3.

Good news: the error has disappeared completely! :smiley: I played several blitz games and finished them without any difficulty (except being beaten hopelessly haha!).

So it seems that this patch has solved the issue indeed!

**Comment by niklasf** [comment]
Just a quick note from me, before I look deeper into this: Yes, python-chess sends isready during early search. Going strictly by the spec, it should be allowed to do that (even if it's a bit unconventional). So a patch on the engine side is definitely the correct thing to do.

Given that other engines also had problems with this in the past, I'll also patch python-chess.

**Comment by kervinck** [comment]
Great! I accept this as a Floyd bug and not a python-chess problem per se, because the UCI specs explicitly state that this scenario must work. If there are follow-up issues, especially hangups or crashes, let me know.

The only side-effect that I can think of is that latest PV, depth and or score will be swallowed and not communicated to the user in these situations. This is a bit cosmetic however, and for use in pico-chess not much of a problem if it works for now. I therefore intend to postpone that to Floyd v0.9 (which might take a few months because I'm working on other projects first).

**Comment by djdekker** [comment]
Hi Niklas,
Just for my understanding... what's the purpose of python-chess sending 'isready' during early search? I'm seeing one engine after the other having difficulties with this situation when using the python-chess/PicoChess combination: Cinnamon, Floyd, K2, GreKo, Rodent etc. Are bad things going to happen if python-chess were to send 'isready' only when the engine is *not* searching?
Greetings,
DJ

**Comment by niklasf** [comment]
Hi. It was useful at some point to detect engines being in an unexpected state (still searching). I plan to get rid of it soon.

**Comment by djdekker** [comment]
Thanks Niklas, alles klar!
