### ISSUE TITLE
Permission errors on uci usage.

### ISSUE THREAD

**Issue by JacoSmit** [niklasf/python-chess#85]
Hi,

I tried to use the uci functionality from your package. I provided to following code but I constantly get a Permision denied error. I tried it using sudo, but no luck. Any ideas on what I can do regarding this? The folders have the correct access rights as well.

```
>>> from chess import uci
>>> engine = uci.popen_engine("./stockfish/Linux/stockfish_7_x64")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/chess/uci.py", line 1349, in popen_engine
    return engine_cls(process)
  File "/usr/local/lib/python2.7/dist-packages/chess/uci.py", line 502, in __init__
    self.process.spawn(self)
  File "/usr/local/lib/python2.7/dist-packages/chess/uci.py", line 370, in spawn
    self.process = subprocess.Popen(self.command, stdout=subprocess.PIPE, stdin=subprocess.PIPE, bufsize=1, universal_newlines=True)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by niklasf** [comment]
You probably have to do `chmod +x ./stockfish/Linux/stockfish_7_x64`.

**Comment by JacoSmit** [comment]
Thank you so much. I feel like a noob now. You can mark this as closed. Great library by the way.
