### ISSUE TITLE
chess.engine.EngineTerminatedException

### ISSUE THREAD

**Issue by Noob-A** [niklasf/python-chess#858]
I get this error:
```
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\web\app.py", line 12, in <module>
    engine.uci()
  File "C:\Users\User\PycharmProjects\web\venv\lib\site-packages\chess\uci.py", line 688, in uci
    return self._queue_command(command, async_callback)
  File "C:\Users\User\PycharmProjects\web\venv\lib\site-packages\chess\uci.py", line 666, in _queue_command
    return future.result(timeout=FUTURE_POLL_TIMEOUT)
  File "C:\Python39\lib\concurrent\futures\_base.py", line 440, in result
    return self.__get_result()
  File "C:\Python39\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "C:\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\User\PycharmProjects\web\venv\lib\site-packages\chess\uci.py", line 686, in command
    raise EngineTerminatedException()
chess.engine.EngineTerminatedException
```

my code is simple, it is from docs:
```python
import asyncio
import chess
import chess.engine


async def main() -> None:
    transport, engine = await chess.engine.popen_uci(
        r"C:\Users\User\Desktop\stockfish_14_win_x64_avx2\stockfish_14_x64_avx2.exe")

    board = chess.Board()
    while not board.is_game_over():
        result = await engine.play(board, chess.engine.Limit(time=0.1))
        board.push(result.move)

    await engine.quit()


asyncio.set_event_loop_policy(chess.engine.EventLoopPolicy())
asyncio.run(main())
```
stockfish versions i tried: 14.1; 14.0

**Comment by niklasf** [comment]
Hi, which version of python-chess are you using?

`print(chess.__version__)`

**Comment by Noob-A** [comment]
1.8.0

**Comment by Noob-A** [comment]
also this code results in the same error:
```
import chess
import chess.engine

engine = chess.engine.SimpleEngine.popen_uci(
    r"C:\Users\Emil\Desktop\stockfish_14_win_x64_avx2\stockfish_14_x64_avx2.exe")

board = chess.Board()
while not board.is_game_over():
    result = engine.play(board, chess.engine.Limit(time=0.1))
    board.push(result.move)

engine.quit()
```

**Comment by niklasf** [comment]
Mhh ... that seems almost impossible. The stacktrace refers to a file that doesn't exist in this version of python-chess.

**Comment by Noob-A** [comment]
ok i will try to install it not on venv

**Comment by Noob-A** [comment]
```
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\stock_test\main.py", line 4, in <module>
    engine = chess.engine.SimpleEngine.popen_uci(
  File "C:\Python39\lib\site-packages\chess\engine.py", line 2824, in popen_uci
    return cls.popen(UciProtocol, command, timeout=timeout, debug=debug, setpgrp=setpgrp, **popen_args)
  File "C:\Python39\lib\site-packages\chess\engine.py", line 2816, in popen
    return run_in_background(background, name=f"{cls.__name__} (command={command!r})", debug=debug)
  File "C:\Python39\lib\site-packages\chess\engine.py", line 201, in run_in_background
    return future.result()
  File "C:\Python39\lib\concurrent\futures\_base.py", line 440, in result
    return self.__get_result()
  File "C:\Python39\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "C:\Python39\lib\site-packages\chess\engine.py", line 195, in background
    asyncio.run(coroutine(future))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Python39\lib\site-packages\chess\engine.py", line 2808, in background
    await asyncio.wait_for(protocol.initialize(), timeout)
  File "C:\Python39\lib\asyncio\tasks.py", line 476, in wait_for
    return fut.result()
  File "C:\Python39\lib\site-packages\chess\engine.py", line 1403, in initialize
    return await self.communicate(UciInitializeCommand)
  File "C:\Python39\lib\site-packages\chess\engine.py", line 1069, in communicate
    return await command.result
chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 3221225501)
```

**Comment by Noob-A** [comment]
```
import chess
import chess.engine

engine = chess.engine.SimpleEngine.popen_uci(
    r"C:\Users\Emil\Desktop\stockfish_14_win_x64_avx2\stockfish_14_x64_avx2.exe")

board = chess.Board()
while not board.is_game_over():
    result = engine.play(board, chess.engine.Limit(time=0.1))
    board.push(result.move)

engine.quit()
```

**Comment by niklasf** [comment]
It looks like your CPU model does not support AVX2. You need to use a more widely compatible Stockfish build.

You can verify this by opening the `stockfish[...].exe` directly and typing bench. It should search a list of benchmark positions and not close/crash.

**Comment by Noob-A** [comment]
yes, i noticed that it crashes, does your lib support this type of stockfish?
![image](https://user-images.githubusercontent.com/59875489/156231028-7e356be3-3672-4fc2-b308-bbd652a1fd71.png)

**Comment by Noob-A** [comment]
```
import chess
import chess.engine

engine = chess.engine.SimpleEngine.popen_uci(
    r"C:\Users\User\Desktop\stockfish_14.1_win_x64_popcnt\stockfish_14.1_win_x64_popcnt.exe")

board = chess.Board()
while not board.is_game_over():
    result = engine.play(board, chess.engine.Limit(time=0.1))
    board.push(result.move)

engine.quit()
```
traceback:
```
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\stock_test\main.py", line 4, in <module>
    engine = chess.engine.SimpleEngine.popen_uci(
  File "C:\Python39\lib\site-packages\chess\engine.py", line 2824, in popen_uci
    return cls.popen(UciProtocol, command, timeout=timeout, debug=debug, setpgrp=setpgrp, **popen_args)
  File "C:\Python39\lib\site-packages\chess\engine.py", line 2816, in popen
    return run_in_background(background, name=f"{cls.__name__} (command={command!r})", debug=debug)
  File "C:\Python39\lib\site-packages\chess\engine.py", line 201, in run_in_background
    return future.result()
  File "C:\Python39\lib\concurrent\futures\_base.py", line 440, in result
    return self.__get_result()
  File "C:\Python39\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "C:\Python39\lib\site-packages\chess\engine.py", line 195, in background
    asyncio.run(coroutine(future))
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Python39\lib\site-packages\chess\engine.py", line 2808, in background
    await asyncio.wait_for(protocol.initialize(), timeout)
  File "C:\Python39\lib\asyncio\tasks.py", line 476, in wait_for
    return fut.result()
  File "C:\Python39\lib\site-packages\chess\engine.py", line 1403, in initialize
    return await self.communicate(UciInitializeCommand)
  File "C:\Python39\lib\site-packages\chess\engine.py", line 1069, in communicate
    return await command.result
chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: 3221225501)
```
