### ISSUE TITLE
Module 'chess' has no attribute 'Board'

### ISSUE THREAD

**Issue by rpdelaney** [niklasf/python-chess#88]
```
$ pip --version
pip 8.1.2 from /usr/lib/python3.5/site-packages (python 3.5)
$ sudo pip install python-chess
Requirement already satisfied (use --upgrade to upgrade): python-chess in /usr/lib/python3.5/site-packages
$ python3
Python 3.5.2 (default, Jun 28 2016, 08:46:01)
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chess
>>> board = chess.Board()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'chess' has no attribute 'Board'
>>> pgn = open('game.pgn')
>>> first_game = chess.pgn.read_game(pgn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'chess' has no attribute 'pgn'
>>> dir(chess)
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> help(chess)
Help on package chess:

NAME
    chess

PACKAGE CONTENTS


FILE
    (built-in)


>>>
```

**Comment by niklasf** [comment]
Please try `import chess; print(chess.__file__)` to see if that matches the path reported by pip.

Second problem: To use the pgn module you'd also have to do `chess.pgn`.

**Comment by sshivaji** [comment]
My suspicion is that your local filesystem from where you are trying to run
the code has a child directory "chess"  for the first error. Can you print
out your current directory and its contents?

For second problem as Niklas says, you need to do "import chess.pgn".

**Comment by rpdelaney** [comment]
```
$ pwd
/tmp
$ stat chess
stat: cannot stat 'chess': No such file or directory
$ python3
Python 3.5.2 (default, Jun 28 2016, 08:46:01)
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chess
>>> print(chess.__file__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'chess' has no attribute '__file__'
>>> import chess.pgn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'chess.pgn'
>>>
```

**Comment by rpdelaney** [comment]
For some reason, it works when I install python-chess in a virtualenv:
```
$ virtualenv -p python3 .
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /tmp/chess/bin/python3
Also creating executable in /tmp/chess/bin/python
Installing setuptools, pip, wheel...done.
$ source bin/act
activate          activate.csh      activate.fish     activate_this.py
$ source bin/activate
(chess) 
$ pip install python-chess
Collecting python-chess
Installing collected packages: python-chess
Successfully installed python-chess-0.14.1
(chess) 
$ python3
Python 3.5.2 (default, Jun 28 2016, 08:46:01)
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chess
>>> import chess.pgn
>>> print(chess.__file__)
/tmp/chess/lib/python3.5/site-packages/chess/__init__.py
>>> pgn = open('/home/ryan/game.pgn')
>>> first_game = chess.pgn.read_game(pgn)
>>> board = chess.Board()
>>>
```
Therefore I'm concluding that this is a problem with my local python/pip setup and not a problem with python-chess. Sorry for the distraction(s).

**Comment by johndpope** [comment]
I'm struggling to get this to work @niklasf with conda 
https://github.com/2014mchidamb/AdversarialChess/issues/2

**Comment by johndpope** [comment]
resolved - need to have conda
upgrade this 
https://anaconda.org/pypi/python-chess

**Comment by hruday007** [comment]
just change file name from chess.py new_chess.py
