### ISSUE TITLE
syzygy probe

### ISSUE THREAD

**Issue by piccoloprogrammatore** [niklasf/python-chess#94]
I've found another position that give me an error.
The code is the following:

import chess.syzygy

tablebases = chess.syzygy.open_tablebases("./syzygy")

board = chess.Board("2k4K/7P/6Q1/4q3/8/8/8/8 w - - 31 123")
print tablebases.probe_dtz(board) 
print tablebases.probe_wdl(board)
tablebases.close()

And the error message is:

Traceback (most recent call last):
  File "./prova.py", line 8, in <module>
    print tablebases.probe_dtz(board) 
  File "/home/fabio/Desktop/python-chess-0.15.1/chess/syzygy.py", line 1591, in probe_dtz
    v = self.probe_dtz_no_ep(board)
  File "/home/fabio/Desktop/python-chess-0.15.1/chess/syzygy.py", line 1490, in probe_dtz_no_ep
    for move in board.generate_legal_moves(~board.pawns, ~board.occupied):
  File "/home/fabio/Desktop/python-chess-0.15.1/chess/__init__.py", line 3499, in generate_evasions
    attacked_square = self.attackers_mask(not self.turn, to_square)
  File "/home/fabio/Desktop/python-chess-0.15.1/chess/__init__.py", line 1586, in attackers_mask
    bb_square = BB_SQUARES[square]
IndexError: list index out of range

**Comment by niklasf** [comment]
Thanks again. Since this is basically the thing (also introduced in v0.15.0) I added more systematic tests for this kind of bug. Releasing v0.15.2 in just a moment.
