### ISSUE TITLE
TypeError: As of 3.10, the *loop* parameter was removed from Event()

### ISSUE THREAD

**Issue by sxre** [niklasf/python-chess#941]
Im trying to run a simple script for testing purposes. The first line of the engine wont even run. What should i do?

Code:

```py
import chess
import chess.engine
import chess.pgn

stockfish_path = r'Engine/stockfish.exe'

engine = chess.engine.SimpleEngine.popen_uci(stockfish_path)
```

Error:

```
C:\Users\rpcdr\Desktop\Sangatsu-master>python test.py
Traceback (most recent call last):
  File "C:\Users\rpcdr\Desktop\Sangatsu-master\test.py", line 7, in <module>
Exception in thread Thread-1 (background):
Traceback (most recent call last):
    engine = chess.engine.SimpleEngine.popen_uci(stockfish_path)
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 2387, in popen_uci
    return cls.popen(UciProtocol, command, timeout=timeout, debug=debug, setpgrp=setpgrp, **popen_args)
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 2379, in popen
    self.run()
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 174, in background
    loop.run_until_complete(asyncio.gather(*pending, loop=loop, return_exceptions=True))
TypeError: gather() got an unexpected keyword argument 'loop'
    return run_in_background(background, debug=debug)
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 186, in run_in_background
    return future.result()
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 165, in background
    loop.run_until_complete(coroutine(future))
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 2369, in background
    simple_engine = cls(transport, protocol, timeout=timeout)
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\site-packages\chess\engine.py", line 2270, in __init__
    self.shutdown_event = asyncio.Event(loop=self.protocol.loop)
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\locks.py", line 168, in __init__
    super().__init__(loop=loop)
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000013F3A1AC0D0>
Traceback (most recent call last):
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 126, in __del__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000013F3A1ADB40>
Traceback (most recent call last):
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 115, in __del__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 79, in __repr__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000013F3A1ADB40>
Traceback (most recent call last):
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 115, in __del__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 79, in __repr__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000013F3A1ADB40>
Traceback (most recent call last):
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 115, in __del__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 79, in __repr__
  File "C:\Users\rpcdr\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe
```

**Comment by niklasf** [comment]
Hi, which version of python-chess are you using?

```python
import chess
print(chess.__version__)
```

**Comment by sxre** [comment]
I was using ```0.29.0```
i updated it and it works perfectly fine now. thanks!
