### ISSUE TITLE
Timeout during stockfish initialization with huge hash table size

### ISSUE THREAD

**Issue by lvd2** [niklasf/python-chess#942]
What I'm trying to do:
```
#!/usr/bin/env python

import chess
import chess.engine
import chess.pgn

board = chess.Board("rnbqkbnr/pp2pppp/2p5/3p4/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3")
engine = chess.engine.SimpleEngine.popen_uci(r"/home/surfin/tmp/src/Stockfish/src/stockfish")
engine.configure({"Threads": 32, "Hash": 32768, "SyzygyPath": "/some/path/Syzygy/3-4-5-6"})
#engine.configure({"Threads": 32, "Hash": 4096, "SyzygyPath": "/some/path/Syzygy/3-4-5-6"})

g=chess.pgn.Game()
g.setup(board)

fm=1

while not board.is_game_over():
    result = engine.play(board, chess.engine.Limit(time=1))
    board.push(result.move)

    if fm==1:
        n=g.add_variation(result.move)
        fm=0
    else:
        n=n.add_variation(result.move)

    print(g)

engine.quit()
```

For hash size of 32 gigabytes, the python-chess fails with a timeout like this:
`$ time ./chkchs.py 
Traceback (most recent call last):
  File "/some/path/pychess/_venv/lib/python3.10/site-packages/chess/engine.py", line 1671, in play
    return await self.communicate(UciPlayCommand)
  File "/some/path/pychess/_venv/lib/python3.10/site-packages/chess/engine.py", line 1080, in communicate
    return await command.result
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/some/path/pychess/./chkchs.py", line 24, in <module>
    result = engine.play(board, chess.engine.Limit(time=1))
  File "/some/path/pychess/_venv/lib/python3.10/site-packages/chess/engine.py", line 2781, in play
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt: 

^C

real    0m17.872s
user    0m0.178s
sys     0m0.042s
`
It also hangs so that only double ctrl-C returns to shell.

For reference, running raw stockfish with only setting the hash table size to the same value takes ~20 seconds:
`
$ time bash -c "echo -e 'setoption name Hash value 32768\nisready\n' | /some/path/Stockfish/src/stockfish"
Stockfish 111122 by the Stockfish developers (see AUTHORS file)
readyok

real    0m20.114s
user    0m2.052s
sys     0m17.805s
`

**Comment by niklasf** [comment]
You can increase the [timeout](https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.SimpleEngine.popen_uci) from the default of 10s like so:

```python
engine = chess.engine.SimpleEngine.popen_uci(r"/some/path/Stockfish/src/stockfish", timeout=30)
```
